package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbArticleContent;
import java.util.List;

public interface EbArticleContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_article_content
     *
     * @mbg.generated
     */
    int insert(EbArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_article_content
     *
     * @mbg.generated
     */
    List<EbArticleContent> selectAll();
}