package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbBillHis;
import java.util.List;

public interface EbBillHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_bill_his
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_bill_his
     *
     * @mbg.generated
     */
    int insert(EbBillHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_bill_his
     *
     * @mbg.generated
     */
    EbBillHis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_bill_his
     *
     * @mbg.generated
     */
    List<EbBillHis> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_bill_his
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbBillHis record);
}