package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbIdCard;
import java.util.List;

public interface EbIdCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_id_card
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long idCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_id_card
     *
     * @mbg.generated
     */
    int insert(EbIdCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_id_card
     *
     * @mbg.generated
     */
    EbIdCard selectByPrimaryKey(Long idCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_id_card
     *
     * @mbg.generated
     */
    List<EbIdCard> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_id_card
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbIdCard record);
}