package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbMerExtract;
import java.util.List;

public interface EbMerExtractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_mer_extract
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_mer_extract
     *
     * @mbg.generated
     */
    int insert(EbMerExtract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_mer_extract
     *
     * @mbg.generated
     */
    EbMerExtract selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_mer_extract
     *
     * @mbg.generated
     */
    List<EbMerExtract> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_mer_extract
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbMerExtract record);
}