package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbRoutineAccessToken;
import java.util.List;

public interface EbRoutineAccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_routine_access_token
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_routine_access_token
     *
     * @mbg.generated
     */
    int insert(EbRoutineAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_routine_access_token
     *
     * @mbg.generated
     */
    EbRoutineAccessToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_routine_access_token
     *
     * @mbg.generated
     */
    List<EbRoutineAccessToken> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_routine_access_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbRoutineAccessToken record);
}