package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbStoreCouponUser;
import java.util.List;

public interface EbStoreCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_coupon_user
     *
     * @mbg.generated
     */
    int insert(EbStoreCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_coupon_user
     *
     * @mbg.generated
     */
    EbStoreCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_coupon_user
     *
     * @mbg.generated
     */
    List<EbStoreCouponUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbStoreCouponUser record);
}