package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbStoreBargainUserHelp;
import java.util.List;

public interface EbStoreBargainUserHelpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_bargain_user_help
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_bargain_user_help
     *
     * @mbg.generated
     */
    int insert(EbStoreBargainUserHelp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_bargain_user_help
     *
     * @mbg.generated
     */
    EbStoreBargainUserHelp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_bargain_user_help
     *
     * @mbg.generated
     */
    List<EbStoreBargainUserHelp> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_bargain_user_help
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbStoreBargainUserHelp record);
}