package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbStoreProductAttr;
import java.util.List;

public interface EbStoreProductAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product_attr
     *
     * @mbg.generated
     */
    int insert(EbStoreProductAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product_attr
     *
     * @mbg.generated
     */
    List<EbStoreProductAttr> selectAll();
}