package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbStoreCombinationAttr;
import java.util.List;

public interface EbStoreCombinationAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_combination_attr
     *
     * @mbg.generated
     */
    int insert(EbStoreCombinationAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_combination_attr
     *
     * @mbg.generated
     */
    List<EbStoreCombinationAttr> selectAll();
}