package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbStoreSeckillAttrValue;
import java.util.List;

public interface EbStoreSeckillAttrValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_seckill_attr_value
     *
     * @mbg.generated
     */
    int insert(EbStoreSeckillAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_seckill_attr_value
     *
     * @mbg.generated
     */
    List<EbStoreSeckillAttrValue> selectAll();
}