package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbStoreOrderCartInfo;
import java.util.List;

public interface EbStoreOrderCartInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_order_cart_info
     *
     * @mbg.generated
     */
    int insert(EbStoreOrderCartInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_order_cart_info
     *
     * @mbg.generated
     */
    List<EbStoreOrderCartInfo> selectAll();
}