package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbStoreProductAttrResult;
import java.util.List;

public interface EbStoreProductAttrResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product_attr_result
     *
     * @mbg.generated
     */
    int insert(EbStoreProductAttrResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product_attr_result
     *
     * @mbg.generated
     */
    List<EbStoreProductAttrResult> selectAll();
}