package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbStoreServiceLog;
import java.util.List;

public interface EbStoreServiceLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_service_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_service_log
     *
     * @mbg.generated
     */
    int insert(EbStoreServiceLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_service_log
     *
     * @mbg.generated
     */
    EbStoreServiceLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_service_log
     *
     * @mbg.generated
     */
    List<EbStoreServiceLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_service_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbStoreServiceLog record);
}