package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbStoreBargainUser;
import java.util.List;

public interface EbStoreBargainUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_bargain_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_bargain_user
     *
     * @mbg.generated
     */
    int insert(EbStoreBargainUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_bargain_user
     *
     * @mbg.generated
     */
    EbStoreBargainUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_bargain_user
     *
     * @mbg.generated
     */
    List<EbStoreBargainUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_bargain_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbStoreBargainUser record);
}