package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbStoreProduct;
import java.util.List;

public interface EbStoreProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    int insert(EbStoreProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    EbStoreProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    List<EbStoreProduct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbStoreProduct record);
}