package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbStoreSeckill;
import java.util.List;

public interface EbStoreSeckillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_seckill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_seckill
     *
     * @mbg.generated
     */
    int insert(EbStoreSeckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_seckill
     *
     * @mbg.generated
     */
    EbStoreSeckill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_seckill
     *
     * @mbg.generated
     */
    List<EbStoreSeckill> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_seckill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbStoreSeckill record);
}