package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbStorePink;
import java.util.List;

public interface EbStorePinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_pink
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_pink
     *
     * @mbg.generated
     */
    int insert(EbStorePink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_pink
     *
     * @mbg.generated
     */
    EbStorePink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_pink
     *
     * @mbg.generated
     */
    List<EbStorePink> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_pink
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbStorePink record);
}