package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbStoreCombination;
import java.util.List;

public interface EbStoreCombinationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_combination
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_combination
     *
     * @mbg.generated
     */
    int insert(EbStoreCombination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_combination
     *
     * @mbg.generated
     */
    EbStoreCombination selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_combination
     *
     * @mbg.generated
     */
    List<EbStoreCombination> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_combination
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbStoreCombination record);
}