package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbStoreCombinationAttrValue;
import java.util.List;

public interface EbStoreCombinationAttrValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_combination_attr_value
     *
     * @mbg.generated
     */
    int insert(EbStoreCombinationAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_combination_attr_value
     *
     * @mbg.generated
     */
    List<EbStoreCombinationAttrValue> selectAll();
}