package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbSystemUserLevel;
import java.util.List;

public interface EbSystemUserLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_user_level
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_user_level
     *
     * @mbg.generated
     */
    int insert(EbSystemUserLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_user_level
     *
     * @mbg.generated
     */
    EbSystemUserLevel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_user_level
     *
     * @mbg.generated
     */
    List<EbSystemUserLevel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_user_level
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbSystemUserLevel record);
}