package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbSystemRole;
import java.util.List;

public interface EbSystemRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    int insert(EbSystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    EbSystemRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    List<EbSystemRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbSystemRole record);
}