package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbSystemAttachment;
import java.util.List;

public interface EbSystemAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_attachment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer attId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_attachment
     *
     * @mbg.generated
     */
    int insert(EbSystemAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_attachment
     *
     * @mbg.generated
     */
    EbSystemAttachment selectByPrimaryKey(Integer attId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_attachment
     *
     * @mbg.generated
     */
    List<EbSystemAttachment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_attachment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbSystemAttachment record);
}