package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbSystemConfig;
import java.util.List;

public interface EbSystemConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_config
     *
     * @mbg.generated
     */
    int insert(EbSystemConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_config
     *
     * @mbg.generated
     */
    EbSystemConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_config
     *
     * @mbg.generated
     */
    List<EbSystemConfig> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbSystemConfig record);
}