package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbToken;
import java.util.List;

public interface EbTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_token
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_token
     *
     * @mbg.generated
     */
    int insert(EbToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_token
     *
     * @mbg.generated
     */
    EbToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_token
     *
     * @mbg.generated
     */
    List<EbToken> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbToken record);
}