package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbUserNotice;
import java.util.List;

public interface EbUserNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_notice
     *
     * @mbg.generated
     */
    int insert(EbUserNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_notice
     *
     * @mbg.generated
     */
    EbUserNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_notice
     *
     * @mbg.generated
     */
    List<EbUserNotice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbUserNotice record);
}