package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbUserBillAwait;
import java.util.List;

public interface EbUserBillAwaitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_bill_await
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_bill_await
     *
     * @mbg.generated
     */
    int insert(EbUserBillAwait record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_bill_await
     *
     * @mbg.generated
     */
    EbUserBillAwait selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_bill_await
     *
     * @mbg.generated
     */
    List<EbUserBillAwait> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_bill_await
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbUserBillAwait record);
}