package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbUserLevel;
import java.util.List;

public interface EbUserLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_level
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_level
     *
     * @mbg.generated
     */
    int insert(EbUserLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_level
     *
     * @mbg.generated
     */
    EbUserLevel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_level
     *
     * @mbg.generated
     */
    List<EbUserLevel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_level
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbUserLevel record);
}