package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbUserGroup;
import java.util.List;

public interface EbUserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_group
     *
     * @mbg.generated
     */
    int insert(EbUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_group
     *
     * @mbg.generated
     */
    EbUserGroup selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_group
     *
     * @mbg.generated
     */
    List<EbUserGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbUserGroup record);
}