package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbUser;
import java.util.List;

public interface EbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    int insert(EbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    EbUser selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    List<EbUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbUser record);
}