package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbUserBill;
import java.util.List;

public interface EbUserBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_bill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_bill
     *
     * @mbg.generated
     */
    int insert(EbUserBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_bill
     *
     * @mbg.generated
     */
    EbUserBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_bill
     *
     * @mbg.generated
     */
    List<EbUserBill> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user_bill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbUserBill record);
}