package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbWechatTemplate;
import java.util.List;

public interface EbWechatTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_wechat_template
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_wechat_template
     *
     * @mbg.generated
     */
    int insert(EbWechatTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_wechat_template
     *
     * @mbg.generated
     */
    EbWechatTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_wechat_template
     *
     * @mbg.generated
     */
    List<EbWechatTemplate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_wechat_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbWechatTemplate record);
}