package com.enjoylearning.mybatis.mapper;

import com.enjoylearning.mybatis.entity.EbWxCashOrderInfo;
import java.util.List;

public interface EbWxCashOrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_wx_cash_order_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long wxCashOrderInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_wx_cash_order_info
     *
     * @mbg.generated
     */
    int insert(EbWxCashOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_wx_cash_order_info
     *
     * @mbg.generated
     */
    EbWxCashOrderInfo selectByPrimaryKey(Long wxCashOrderInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_wx_cash_order_info
     *
     * @mbg.generated
     */
    List<EbWxCashOrderInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_wx_cash_order_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbWxCashOrderInfo record);
}