package com.enjoylearning.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_article_category
 */
public class EbArticleCategory extends BaseEntity {
    /**
     * Database Column Remarks:
     *   文章分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article_category.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   父级ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article_category.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     * Database Column Remarks:
     *   文章分类标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article_category.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   文章分类简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article_category.intr
     *
     * @mbg.generated
     */
    private String intr;

    /**
     * Database Column Remarks:
     *   文章分类图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article_category.image
     *
     * @mbg.generated
     */
    private String image;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article_category.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article_category.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   1删除0未删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article_category.is_del
     *
     * @mbg.generated
     */
    private Boolean isDel;

    /**
     * Database Column Remarks:
     *   添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article_category.add_time
     *
     * @mbg.generated
     */
    private String addTime;

    /**
     * Database Column Remarks:
     *   是否隐藏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article_category.hidden
     *
     * @mbg.generated
     */
    private Boolean hidden;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article_category.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article_category.id
     *
     * @return the value of eb_article_category.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article_category.id
     *
     * @param id the value for eb_article_category.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article_category.pid
     *
     * @return the value of eb_article_category.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article_category.pid
     *
     * @param pid the value for eb_article_category.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article_category.title
     *
     * @return the value of eb_article_category.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article_category.title
     *
     * @param title the value for eb_article_category.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article_category.intr
     *
     * @return the value of eb_article_category.intr
     *
     * @mbg.generated
     */
    public String getIntr() {
        return intr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article_category.intr
     *
     * @param intr the value for eb_article_category.intr
     *
     * @mbg.generated
     */
    public void setIntr(String intr) {
        this.intr = intr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article_category.image
     *
     * @return the value of eb_article_category.image
     *
     * @mbg.generated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article_category.image
     *
     * @param image the value for eb_article_category.image
     *
     * @mbg.generated
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article_category.status
     *
     * @return the value of eb_article_category.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article_category.status
     *
     * @param status the value for eb_article_category.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article_category.sort
     *
     * @return the value of eb_article_category.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article_category.sort
     *
     * @param sort the value for eb_article_category.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article_category.is_del
     *
     * @return the value of eb_article_category.is_del
     *
     * @mbg.generated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article_category.is_del
     *
     * @param isDel the value for eb_article_category.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article_category.add_time
     *
     * @return the value of eb_article_category.add_time
     *
     * @mbg.generated
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article_category.add_time
     *
     * @param addTime the value for eb_article_category.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article_category.hidden
     *
     * @return the value of eb_article_category.hidden
     *
     * @mbg.generated
     */
    public Boolean getHidden() {
        return hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article_category.hidden
     *
     * @param hidden the value for eb_article_category.hidden
     *
     * @mbg.generated
     */
    public void setHidden(Boolean hidden) {
        this.hidden = hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article_category.ctime
     *
     * @return the value of eb_article_category.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article_category.ctime
     *
     * @param ctime the value for eb_article_category.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}