package com.enjoylearning.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_article
 */
public class EbArticle extends BaseEntity {
    /**
     * Database Column Remarks:
     *   文章管理ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.cid
     *
     * @mbg.generated
     */
    private String cid;

    /**
     * Database Column Remarks:
     *   文章标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   文章作者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     * Database Column Remarks:
     *   文章图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.image_input
     *
     * @mbg.generated
     */
    private String imageInput;

    /**
     * Database Column Remarks:
     *   文章简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.synopsis
     *
     * @mbg.generated
     */
    private String synopsis;

    /**
     * Database Column Remarks:
     *   文章分享标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.share_title
     *
     * @mbg.generated
     */
    private String shareTitle;

    /**
     * Database Column Remarks:
     *   文章分享简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.share_synopsis
     *
     * @mbg.generated
     */
    private String shareSynopsis;

    /**
     * Database Column Remarks:
     *   浏览次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.visit
     *
     * @mbg.generated
     */
    private String visit;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   原文链接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.add_time
     *
     * @mbg.generated
     */
    private String addTime;

    /**
     * Database Column Remarks:
     *   是否隐藏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.hide
     *
     * @mbg.generated
     */
    private Boolean hide;

    /**
     * Database Column Remarks:
     *   管理员id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.admin_id
     *
     * @mbg.generated
     */
    private Integer adminId;

    /**
     * Database Column Remarks:
     *   商户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.mer_id
     *
     * @mbg.generated
     */
    private Integer merId;

    /**
     * Database Column Remarks:
     *   是否热门(小程序)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.is_hot
     *
     * @mbg.generated
     */
    private Boolean isHot;

    /**
     * Database Column Remarks:
     *   是否轮播图(小程序)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.is_banner
     *
     * @mbg.generated
     */
    private Boolean isBanner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_article.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.id
     *
     * @return the value of eb_article.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.id
     *
     * @param id the value for eb_article.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.cid
     *
     * @return the value of eb_article.cid
     *
     * @mbg.generated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.cid
     *
     * @param cid the value for eb_article.cid
     *
     * @mbg.generated
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.title
     *
     * @return the value of eb_article.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.title
     *
     * @param title the value for eb_article.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.author
     *
     * @return the value of eb_article.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.author
     *
     * @param author the value for eb_article.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.image_input
     *
     * @return the value of eb_article.image_input
     *
     * @mbg.generated
     */
    public String getImageInput() {
        return imageInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.image_input
     *
     * @param imageInput the value for eb_article.image_input
     *
     * @mbg.generated
     */
    public void setImageInput(String imageInput) {
        this.imageInput = imageInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.synopsis
     *
     * @return the value of eb_article.synopsis
     *
     * @mbg.generated
     */
    public String getSynopsis() {
        return synopsis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.synopsis
     *
     * @param synopsis the value for eb_article.synopsis
     *
     * @mbg.generated
     */
    public void setSynopsis(String synopsis) {
        this.synopsis = synopsis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.share_title
     *
     * @return the value of eb_article.share_title
     *
     * @mbg.generated
     */
    public String getShareTitle() {
        return shareTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.share_title
     *
     * @param shareTitle the value for eb_article.share_title
     *
     * @mbg.generated
     */
    public void setShareTitle(String shareTitle) {
        this.shareTitle = shareTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.share_synopsis
     *
     * @return the value of eb_article.share_synopsis
     *
     * @mbg.generated
     */
    public String getShareSynopsis() {
        return shareSynopsis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.share_synopsis
     *
     * @param shareSynopsis the value for eb_article.share_synopsis
     *
     * @mbg.generated
     */
    public void setShareSynopsis(String shareSynopsis) {
        this.shareSynopsis = shareSynopsis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.visit
     *
     * @return the value of eb_article.visit
     *
     * @mbg.generated
     */
    public String getVisit() {
        return visit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.visit
     *
     * @param visit the value for eb_article.visit
     *
     * @mbg.generated
     */
    public void setVisit(String visit) {
        this.visit = visit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.sort
     *
     * @return the value of eb_article.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.sort
     *
     * @param sort the value for eb_article.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.url
     *
     * @return the value of eb_article.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.url
     *
     * @param url the value for eb_article.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.status
     *
     * @return the value of eb_article.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.status
     *
     * @param status the value for eb_article.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.add_time
     *
     * @return the value of eb_article.add_time
     *
     * @mbg.generated
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.add_time
     *
     * @param addTime the value for eb_article.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.hide
     *
     * @return the value of eb_article.hide
     *
     * @mbg.generated
     */
    public Boolean getHide() {
        return hide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.hide
     *
     * @param hide the value for eb_article.hide
     *
     * @mbg.generated
     */
    public void setHide(Boolean hide) {
        this.hide = hide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.admin_id
     *
     * @return the value of eb_article.admin_id
     *
     * @mbg.generated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.admin_id
     *
     * @param adminId the value for eb_article.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.mer_id
     *
     * @return the value of eb_article.mer_id
     *
     * @mbg.generated
     */
    public Integer getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.mer_id
     *
     * @param merId the value for eb_article.mer_id
     *
     * @mbg.generated
     */
    public void setMerId(Integer merId) {
        this.merId = merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.is_hot
     *
     * @return the value of eb_article.is_hot
     *
     * @mbg.generated
     */
    public Boolean getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.is_hot
     *
     * @param isHot the value for eb_article.is_hot
     *
     * @mbg.generated
     */
    public void setIsHot(Boolean isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.is_banner
     *
     * @return the value of eb_article.is_banner
     *
     * @mbg.generated
     */
    public Boolean getIsBanner() {
        return isBanner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.is_banner
     *
     * @param isBanner the value for eb_article.is_banner
     *
     * @mbg.generated
     */
    public void setIsBanner(Boolean isBanner) {
        this.isBanner = isBanner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_article.ctime
     *
     * @return the value of eb_article.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_article.ctime
     *
     * @param ctime the value for eb_article.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}