package com.enjoylearning.mybatis.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_bill_his
 */
public class EbBillHis extends BaseEntity {
    /**
     * Database Column Remarks:
     *   账单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   中台与销方的结算单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.settle_id_get
     *
     * @mbg.generated
     */
    private Integer settleIdGet;

    /**
     * Database Column Remarks:
     *   中台与供方的结算单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.settle_id_supply
     *
     * @mbg.generated
     */
    private Integer settleIdSupply;

    /**
     * Database Column Remarks:
     *   关联单据id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.link_id
     *
     * @mbg.generated
     */
    private String linkId;

    /**
     * Database Column Remarks:
     *   交易号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.txid
     *
     * @mbg.generated
     */
    private String txid;

    /**
     * Database Column Remarks:
     *   联盟订单号（流水号）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     * Database Column Remarks:
     *   商品名称（含规格属性）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.goods_speci
     *
     * @mbg.generated
     */
    private String goodsSpeci;

    /**
     * Database Column Remarks:
     *   销方商户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.mer_get
     *
     * @mbg.generated
     */
    private Integer merGet;

    /**
     * Database Column Remarks:
     *   供方商户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.mer_supply
     *
     * @mbg.generated
     */
    private Integer merSupply;

    /**
     * Database Column Remarks:
     *   0 = 支出 1 = 获得（此字段暂时放着）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.pm
     *
     * @mbg.generated
     */
    private Boolean pm;

    /**
     * Database Column Remarks:
     *   销方消费者支付金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.money_consumer
     *
     * @mbg.generated
     */
    private BigDecimal moneyConsumer;

    /**
     * Database Column Remarks:
     *   销方消费者申请退款金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.money_back_apply
     *
     * @mbg.generated
     */
    private BigDecimal moneyBackApply;

    /**
     * Database Column Remarks:
     *   实际退给消费者的金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.money_back_real
     *
     * @mbg.generated
     */
    private BigDecimal moneyBackReal;

    /**
     * Database Column Remarks:
     *   商品件数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.cou
     *
     * @mbg.generated
     */
    private Integer cou;

    /**
     * Database Column Remarks:
     *   中台成本价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.cost
     *
     * @mbg.generated
     */
    private BigDecimal cost;

    /**
     * Database Column Remarks:
     *   销方拟结算金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.money_get
     *
     * @mbg.generated
     */
    private BigDecimal moneyGet;

    /**
     * Database Column Remarks:
     *   销方结算金额退款（红字）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.money_get_back
     *
     * @mbg.generated
     */
    private BigDecimal moneyGetBack;

    /**
     * Database Column Remarks:
     *   销方结算金额确定
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.money_get_settle
     *
     * @mbg.generated
     */
    private BigDecimal moneyGetSettle;

    /**
     * Database Column Remarks:
     *   供方成本价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.source_cost
     *
     * @mbg.generated
     */
    private BigDecimal sourceCost;

    /**
     * Database Column Remarks:
     *   供方拟结算金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.money_supply
     *
     * @mbg.generated
     */
    private BigDecimal moneySupply;

    /**
     * Database Column Remarks:
     *   供方结算金额退款（红字）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.money_supply_back
     *
     * @mbg.generated
     */
    private BigDecimal moneySupplyBack;

    /**
     * Database Column Remarks:
     *   供方结算金额确定
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.money_supply_settle
     *
     * @mbg.generated
     */
    private BigDecimal moneySupplySettle;

    /**
     * Database Column Remarks:
     *   中台利润
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.cen_profit
     *
     * @mbg.generated
     */
    private BigDecimal cenProfit;

    /**
     * Database Column Remarks:
     *   中台利润退款（红字）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.cen_profit_back
     *
     * @mbg.generated
     */
    private BigDecimal cenProfitBack;

    /**
     * Database Column Remarks:
     *   实际利润
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.cen_profit_real
     *
     * @mbg.generated
     */
    private BigDecimal cenProfitReal;

    /**
     * Database Column Remarks:
     *   实际退款比例
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.ratio_money_back
     *
     * @mbg.generated
     */
    private BigDecimal ratioMoneyBack;

    /**
     * Database Column Remarks:
     *   摘要
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   明细种类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.category
     *
     * @mbg.generated
     */
    private String category;

    /**
     * Database Column Remarks:
     *   明细类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     * Database Column Remarks:
     *   交易日期或时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.ts_datetime
     *
     * @mbg.generated
     */
    private Date tsDatetime;

    /**
     * Database Column Remarks:
     *   创建时间（后台操作时间）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     * Database Column Remarks:
     *   1=有效，0=未生效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   汇款人(或公司
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.remitter
     *
     * @mbg.generated
     */
    private String remitter;

    /**
     * Database Column Remarks:
     *   汇款方账户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.remitter_account
     *
     * @mbg.generated
     */
    private String remitterAccount;

    /**
     * Database Column Remarks:
     *   汇款银行/线上渠道
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.money_from
     *
     * @mbg.generated
     */
    private String moneyFrom;

    /**
     * Database Column Remarks:
     *   线下汇款方式 1 银行 2 微信 3 支付宝  
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.offline_pay_type
     *
     * @mbg.generated
     */
    private Integer offlinePayType;

    /**
     * Database Column Remarks:
     *   记账时间（确认收货时间点）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * Database Column Remarks:
     *   汇款凭证
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_his.pay_document
     *
     * @mbg.generated
     */
    private String payDocument;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.id
     *
     * @return the value of eb_bill_his.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.id
     *
     * @param id the value for eb_bill_his.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.settle_id_get
     *
     * @return the value of eb_bill_his.settle_id_get
     *
     * @mbg.generated
     */
    public Integer getSettleIdGet() {
        return settleIdGet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.settle_id_get
     *
     * @param settleIdGet the value for eb_bill_his.settle_id_get
     *
     * @mbg.generated
     */
    public void setSettleIdGet(Integer settleIdGet) {
        this.settleIdGet = settleIdGet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.settle_id_supply
     *
     * @return the value of eb_bill_his.settle_id_supply
     *
     * @mbg.generated
     */
    public Integer getSettleIdSupply() {
        return settleIdSupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.settle_id_supply
     *
     * @param settleIdSupply the value for eb_bill_his.settle_id_supply
     *
     * @mbg.generated
     */
    public void setSettleIdSupply(Integer settleIdSupply) {
        this.settleIdSupply = settleIdSupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.link_id
     *
     * @return the value of eb_bill_his.link_id
     *
     * @mbg.generated
     */
    public String getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.link_id
     *
     * @param linkId the value for eb_bill_his.link_id
     *
     * @mbg.generated
     */
    public void setLinkId(String linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.txid
     *
     * @return the value of eb_bill_his.txid
     *
     * @mbg.generated
     */
    public String getTxid() {
        return txid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.txid
     *
     * @param txid the value for eb_bill_his.txid
     *
     * @mbg.generated
     */
    public void setTxid(String txid) {
        this.txid = txid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.order_id
     *
     * @return the value of eb_bill_his.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.order_id
     *
     * @param orderId the value for eb_bill_his.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.goods_speci
     *
     * @return the value of eb_bill_his.goods_speci
     *
     * @mbg.generated
     */
    public String getGoodsSpeci() {
        return goodsSpeci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.goods_speci
     *
     * @param goodsSpeci the value for eb_bill_his.goods_speci
     *
     * @mbg.generated
     */
    public void setGoodsSpeci(String goodsSpeci) {
        this.goodsSpeci = goodsSpeci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.mer_get
     *
     * @return the value of eb_bill_his.mer_get
     *
     * @mbg.generated
     */
    public Integer getMerGet() {
        return merGet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.mer_get
     *
     * @param merGet the value for eb_bill_his.mer_get
     *
     * @mbg.generated
     */
    public void setMerGet(Integer merGet) {
        this.merGet = merGet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.mer_supply
     *
     * @return the value of eb_bill_his.mer_supply
     *
     * @mbg.generated
     */
    public Integer getMerSupply() {
        return merSupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.mer_supply
     *
     * @param merSupply the value for eb_bill_his.mer_supply
     *
     * @mbg.generated
     */
    public void setMerSupply(Integer merSupply) {
        this.merSupply = merSupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.pm
     *
     * @return the value of eb_bill_his.pm
     *
     * @mbg.generated
     */
    public Boolean getPm() {
        return pm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.pm
     *
     * @param pm the value for eb_bill_his.pm
     *
     * @mbg.generated
     */
    public void setPm(Boolean pm) {
        this.pm = pm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.money_consumer
     *
     * @return the value of eb_bill_his.money_consumer
     *
     * @mbg.generated
     */
    public BigDecimal getMoneyConsumer() {
        return moneyConsumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.money_consumer
     *
     * @param moneyConsumer the value for eb_bill_his.money_consumer
     *
     * @mbg.generated
     */
    public void setMoneyConsumer(BigDecimal moneyConsumer) {
        this.moneyConsumer = moneyConsumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.money_back_apply
     *
     * @return the value of eb_bill_his.money_back_apply
     *
     * @mbg.generated
     */
    public BigDecimal getMoneyBackApply() {
        return moneyBackApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.money_back_apply
     *
     * @param moneyBackApply the value for eb_bill_his.money_back_apply
     *
     * @mbg.generated
     */
    public void setMoneyBackApply(BigDecimal moneyBackApply) {
        this.moneyBackApply = moneyBackApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.money_back_real
     *
     * @return the value of eb_bill_his.money_back_real
     *
     * @mbg.generated
     */
    public BigDecimal getMoneyBackReal() {
        return moneyBackReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.money_back_real
     *
     * @param moneyBackReal the value for eb_bill_his.money_back_real
     *
     * @mbg.generated
     */
    public void setMoneyBackReal(BigDecimal moneyBackReal) {
        this.moneyBackReal = moneyBackReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.cou
     *
     * @return the value of eb_bill_his.cou
     *
     * @mbg.generated
     */
    public Integer getCou() {
        return cou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.cou
     *
     * @param cou the value for eb_bill_his.cou
     *
     * @mbg.generated
     */
    public void setCou(Integer cou) {
        this.cou = cou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.cost
     *
     * @return the value of eb_bill_his.cost
     *
     * @mbg.generated
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.cost
     *
     * @param cost the value for eb_bill_his.cost
     *
     * @mbg.generated
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.money_get
     *
     * @return the value of eb_bill_his.money_get
     *
     * @mbg.generated
     */
    public BigDecimal getMoneyGet() {
        return moneyGet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.money_get
     *
     * @param moneyGet the value for eb_bill_his.money_get
     *
     * @mbg.generated
     */
    public void setMoneyGet(BigDecimal moneyGet) {
        this.moneyGet = moneyGet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.money_get_back
     *
     * @return the value of eb_bill_his.money_get_back
     *
     * @mbg.generated
     */
    public BigDecimal getMoneyGetBack() {
        return moneyGetBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.money_get_back
     *
     * @param moneyGetBack the value for eb_bill_his.money_get_back
     *
     * @mbg.generated
     */
    public void setMoneyGetBack(BigDecimal moneyGetBack) {
        this.moneyGetBack = moneyGetBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.money_get_settle
     *
     * @return the value of eb_bill_his.money_get_settle
     *
     * @mbg.generated
     */
    public BigDecimal getMoneyGetSettle() {
        return moneyGetSettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.money_get_settle
     *
     * @param moneyGetSettle the value for eb_bill_his.money_get_settle
     *
     * @mbg.generated
     */
    public void setMoneyGetSettle(BigDecimal moneyGetSettle) {
        this.moneyGetSettle = moneyGetSettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.source_cost
     *
     * @return the value of eb_bill_his.source_cost
     *
     * @mbg.generated
     */
    public BigDecimal getSourceCost() {
        return sourceCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.source_cost
     *
     * @param sourceCost the value for eb_bill_his.source_cost
     *
     * @mbg.generated
     */
    public void setSourceCost(BigDecimal sourceCost) {
        this.sourceCost = sourceCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.money_supply
     *
     * @return the value of eb_bill_his.money_supply
     *
     * @mbg.generated
     */
    public BigDecimal getMoneySupply() {
        return moneySupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.money_supply
     *
     * @param moneySupply the value for eb_bill_his.money_supply
     *
     * @mbg.generated
     */
    public void setMoneySupply(BigDecimal moneySupply) {
        this.moneySupply = moneySupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.money_supply_back
     *
     * @return the value of eb_bill_his.money_supply_back
     *
     * @mbg.generated
     */
    public BigDecimal getMoneySupplyBack() {
        return moneySupplyBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.money_supply_back
     *
     * @param moneySupplyBack the value for eb_bill_his.money_supply_back
     *
     * @mbg.generated
     */
    public void setMoneySupplyBack(BigDecimal moneySupplyBack) {
        this.moneySupplyBack = moneySupplyBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.money_supply_settle
     *
     * @return the value of eb_bill_his.money_supply_settle
     *
     * @mbg.generated
     */
    public BigDecimal getMoneySupplySettle() {
        return moneySupplySettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.money_supply_settle
     *
     * @param moneySupplySettle the value for eb_bill_his.money_supply_settle
     *
     * @mbg.generated
     */
    public void setMoneySupplySettle(BigDecimal moneySupplySettle) {
        this.moneySupplySettle = moneySupplySettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.cen_profit
     *
     * @return the value of eb_bill_his.cen_profit
     *
     * @mbg.generated
     */
    public BigDecimal getCenProfit() {
        return cenProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.cen_profit
     *
     * @param cenProfit the value for eb_bill_his.cen_profit
     *
     * @mbg.generated
     */
    public void setCenProfit(BigDecimal cenProfit) {
        this.cenProfit = cenProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.cen_profit_back
     *
     * @return the value of eb_bill_his.cen_profit_back
     *
     * @mbg.generated
     */
    public BigDecimal getCenProfitBack() {
        return cenProfitBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.cen_profit_back
     *
     * @param cenProfitBack the value for eb_bill_his.cen_profit_back
     *
     * @mbg.generated
     */
    public void setCenProfitBack(BigDecimal cenProfitBack) {
        this.cenProfitBack = cenProfitBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.cen_profit_real
     *
     * @return the value of eb_bill_his.cen_profit_real
     *
     * @mbg.generated
     */
    public BigDecimal getCenProfitReal() {
        return cenProfitReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.cen_profit_real
     *
     * @param cenProfitReal the value for eb_bill_his.cen_profit_real
     *
     * @mbg.generated
     */
    public void setCenProfitReal(BigDecimal cenProfitReal) {
        this.cenProfitReal = cenProfitReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.ratio_money_back
     *
     * @return the value of eb_bill_his.ratio_money_back
     *
     * @mbg.generated
     */
    public BigDecimal getRatioMoneyBack() {
        return ratioMoneyBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.ratio_money_back
     *
     * @param ratioMoneyBack the value for eb_bill_his.ratio_money_back
     *
     * @mbg.generated
     */
    public void setRatioMoneyBack(BigDecimal ratioMoneyBack) {
        this.ratioMoneyBack = ratioMoneyBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.title
     *
     * @return the value of eb_bill_his.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.title
     *
     * @param title the value for eb_bill_his.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.category
     *
     * @return the value of eb_bill_his.category
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.category
     *
     * @param category the value for eb_bill_his.category
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.type
     *
     * @return the value of eb_bill_his.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.type
     *
     * @param type the value for eb_bill_his.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.mark
     *
     * @return the value of eb_bill_his.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.mark
     *
     * @param mark the value for eb_bill_his.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.ts_datetime
     *
     * @return the value of eb_bill_his.ts_datetime
     *
     * @mbg.generated
     */
    public Date getTsDatetime() {
        return tsDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.ts_datetime
     *
     * @param tsDatetime the value for eb_bill_his.ts_datetime
     *
     * @mbg.generated
     */
    public void setTsDatetime(Date tsDatetime) {
        this.tsDatetime = tsDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.add_time
     *
     * @return the value of eb_bill_his.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.add_time
     *
     * @param addTime the value for eb_bill_his.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.status
     *
     * @return the value of eb_bill_his.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.status
     *
     * @param status the value for eb_bill_his.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.remitter
     *
     * @return the value of eb_bill_his.remitter
     *
     * @mbg.generated
     */
    public String getRemitter() {
        return remitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.remitter
     *
     * @param remitter the value for eb_bill_his.remitter
     *
     * @mbg.generated
     */
    public void setRemitter(String remitter) {
        this.remitter = remitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.remitter_account
     *
     * @return the value of eb_bill_his.remitter_account
     *
     * @mbg.generated
     */
    public String getRemitterAccount() {
        return remitterAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.remitter_account
     *
     * @param remitterAccount the value for eb_bill_his.remitter_account
     *
     * @mbg.generated
     */
    public void setRemitterAccount(String remitterAccount) {
        this.remitterAccount = remitterAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.money_from
     *
     * @return the value of eb_bill_his.money_from
     *
     * @mbg.generated
     */
    public String getMoneyFrom() {
        return moneyFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.money_from
     *
     * @param moneyFrom the value for eb_bill_his.money_from
     *
     * @mbg.generated
     */
    public void setMoneyFrom(String moneyFrom) {
        this.moneyFrom = moneyFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.offline_pay_type
     *
     * @return the value of eb_bill_his.offline_pay_type
     *
     * @mbg.generated
     */
    public Integer getOfflinePayType() {
        return offlinePayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.offline_pay_type
     *
     * @param offlinePayType the value for eb_bill_his.offline_pay_type
     *
     * @mbg.generated
     */
    public void setOfflinePayType(Integer offlinePayType) {
        this.offlinePayType = offlinePayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.ctime
     *
     * @return the value of eb_bill_his.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.ctime
     *
     * @param ctime the value for eb_bill_his.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_his.pay_document
     *
     * @return the value of eb_bill_his.pay_document
     *
     * @mbg.generated
     */
    public String getPayDocument() {
        return payDocument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_his.pay_document
     *
     * @param payDocument the value for eb_bill_his.pay_document
     *
     * @mbg.generated
     */
    public void setPayDocument(String payDocument) {
        this.payDocument = payDocument;
    }
}