package com.enjoylearning.mybatis.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_bill_summary
 */
public class EbBillSummary extends BaseEntity {
    /**
     * Database Column Remarks:
     *   结算单ID（自动增长）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_summary.settle_id
     *
     * @mbg.generated
     */
    private Integer settleId;

    /**
     * Database Column Remarks:
     *   结算类型：供货 拿货
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_summary.settle_type
     *
     * @mbg.generated
     */
    private String settleType;

    /**
     * Database Column Remarks:
     *   生成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_summary.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * Database Column Remarks:
     *   账单日期范围开始
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_summary.date_start
     *
     * @mbg.generated
     */
    private Date dateStart;

    /**
     * Database Column Remarks:
     *   账单日期范围截止
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_summary.date_end
     *
     * @mbg.generated
     */
    private Date dateEnd;

    /**
     * Database Column Remarks:
     *   商户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_summary.mer_id
     *
     * @mbg.generated
     */
    private Integer merId;

    /**
     * Database Column Remarks:
     *   商家名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_summary.mer_name
     *
     * @mbg.generated
     */
    private String merName;

    /**
     * Database Column Remarks:
     *   本期商品数量总计
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_summary.count_settle
     *
     * @mbg.generated
     */
    private Integer countSettle;

    /**
     * Database Column Remarks:
     *   本期结算金额汇总
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_summary.money_settle
     *
     * @mbg.generated
     */
    private BigDecimal moneySettle;

    /**
     * Database Column Remarks:
     *   0初始 1财务确认
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_summary.finance_checked
     *
     * @mbg.generated
     */
    private Byte financeChecked;

    /**
     * Database Column Remarks:
     *   财务人员用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_summary.financecheck_person
     *
     * @mbg.generated
     */
    private String financecheckPerson;

    /**
     * Database Column Remarks:
     *   财务确认时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_summary.ctime_finance
     *
     * @mbg.generated
     */
    private Date ctimeFinance;

    /**
     * Database Column Remarks:
     *   0初始 1商家确认
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_summary.mer_checked
     *
     * @mbg.generated
     */
    private Byte merChecked;

    /**
     * Database Column Remarks:
     *   商户确认人员用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_summary.mercheck_person
     *
     * @mbg.generated
     */
    private String mercheckPerson;

    /**
     * Database Column Remarks:
     *   商家确认时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_summary.ctime_mer
     *
     * @mbg.generated
     */
    private Date ctimeMer;

    /**
     * Database Column Remarks:
     *   汇总过程完成时间点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_bill_summary.ctime_finished
     *
     * @mbg.generated
     */
    private Date ctimeFinished;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_summary.settle_id
     *
     * @return the value of eb_bill_summary.settle_id
     *
     * @mbg.generated
     */
    public Integer getSettleId() {
        return settleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_summary.settle_id
     *
     * @param settleId the value for eb_bill_summary.settle_id
     *
     * @mbg.generated
     */
    public void setSettleId(Integer settleId) {
        this.settleId = settleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_summary.settle_type
     *
     * @return the value of eb_bill_summary.settle_type
     *
     * @mbg.generated
     */
    public String getSettleType() {
        return settleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_summary.settle_type
     *
     * @param settleType the value for eb_bill_summary.settle_type
     *
     * @mbg.generated
     */
    public void setSettleType(String settleType) {
        this.settleType = settleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_summary.ctime
     *
     * @return the value of eb_bill_summary.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_summary.ctime
     *
     * @param ctime the value for eb_bill_summary.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_summary.date_start
     *
     * @return the value of eb_bill_summary.date_start
     *
     * @mbg.generated
     */
    public Date getDateStart() {
        return dateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_summary.date_start
     *
     * @param dateStart the value for eb_bill_summary.date_start
     *
     * @mbg.generated
     */
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_summary.date_end
     *
     * @return the value of eb_bill_summary.date_end
     *
     * @mbg.generated
     */
    public Date getDateEnd() {
        return dateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_summary.date_end
     *
     * @param dateEnd the value for eb_bill_summary.date_end
     *
     * @mbg.generated
     */
    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_summary.mer_id
     *
     * @return the value of eb_bill_summary.mer_id
     *
     * @mbg.generated
     */
    public Integer getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_summary.mer_id
     *
     * @param merId the value for eb_bill_summary.mer_id
     *
     * @mbg.generated
     */
    public void setMerId(Integer merId) {
        this.merId = merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_summary.mer_name
     *
     * @return the value of eb_bill_summary.mer_name
     *
     * @mbg.generated
     */
    public String getMerName() {
        return merName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_summary.mer_name
     *
     * @param merName the value for eb_bill_summary.mer_name
     *
     * @mbg.generated
     */
    public void setMerName(String merName) {
        this.merName = merName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_summary.count_settle
     *
     * @return the value of eb_bill_summary.count_settle
     *
     * @mbg.generated
     */
    public Integer getCountSettle() {
        return countSettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_summary.count_settle
     *
     * @param countSettle the value for eb_bill_summary.count_settle
     *
     * @mbg.generated
     */
    public void setCountSettle(Integer countSettle) {
        this.countSettle = countSettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_summary.money_settle
     *
     * @return the value of eb_bill_summary.money_settle
     *
     * @mbg.generated
     */
    public BigDecimal getMoneySettle() {
        return moneySettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_summary.money_settle
     *
     * @param moneySettle the value for eb_bill_summary.money_settle
     *
     * @mbg.generated
     */
    public void setMoneySettle(BigDecimal moneySettle) {
        this.moneySettle = moneySettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_summary.finance_checked
     *
     * @return the value of eb_bill_summary.finance_checked
     *
     * @mbg.generated
     */
    public Byte getFinanceChecked() {
        return financeChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_summary.finance_checked
     *
     * @param financeChecked the value for eb_bill_summary.finance_checked
     *
     * @mbg.generated
     */
    public void setFinanceChecked(Byte financeChecked) {
        this.financeChecked = financeChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_summary.financecheck_person
     *
     * @return the value of eb_bill_summary.financecheck_person
     *
     * @mbg.generated
     */
    public String getFinancecheckPerson() {
        return financecheckPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_summary.financecheck_person
     *
     * @param financecheckPerson the value for eb_bill_summary.financecheck_person
     *
     * @mbg.generated
     */
    public void setFinancecheckPerson(String financecheckPerson) {
        this.financecheckPerson = financecheckPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_summary.ctime_finance
     *
     * @return the value of eb_bill_summary.ctime_finance
     *
     * @mbg.generated
     */
    public Date getCtimeFinance() {
        return ctimeFinance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_summary.ctime_finance
     *
     * @param ctimeFinance the value for eb_bill_summary.ctime_finance
     *
     * @mbg.generated
     */
    public void setCtimeFinance(Date ctimeFinance) {
        this.ctimeFinance = ctimeFinance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_summary.mer_checked
     *
     * @return the value of eb_bill_summary.mer_checked
     *
     * @mbg.generated
     */
    public Byte getMerChecked() {
        return merChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_summary.mer_checked
     *
     * @param merChecked the value for eb_bill_summary.mer_checked
     *
     * @mbg.generated
     */
    public void setMerChecked(Byte merChecked) {
        this.merChecked = merChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_summary.mercheck_person
     *
     * @return the value of eb_bill_summary.mercheck_person
     *
     * @mbg.generated
     */
    public String getMercheckPerson() {
        return mercheckPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_summary.mercheck_person
     *
     * @param mercheckPerson the value for eb_bill_summary.mercheck_person
     *
     * @mbg.generated
     */
    public void setMercheckPerson(String mercheckPerson) {
        this.mercheckPerson = mercheckPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_summary.ctime_mer
     *
     * @return the value of eb_bill_summary.ctime_mer
     *
     * @mbg.generated
     */
    public Date getCtimeMer() {
        return ctimeMer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_summary.ctime_mer
     *
     * @param ctimeMer the value for eb_bill_summary.ctime_mer
     *
     * @mbg.generated
     */
    public void setCtimeMer(Date ctimeMer) {
        this.ctimeMer = ctimeMer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_bill_summary.ctime_finished
     *
     * @return the value of eb_bill_summary.ctime_finished
     *
     * @mbg.generated
     */
    public Date getCtimeFinished() {
        return ctimeFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_bill_summary.ctime_finished
     *
     * @param ctimeFinished the value for eb_bill_summary.ctime_finished
     *
     * @mbg.generated
     */
    public void setCtimeFinished(Date ctimeFinished) {
        this.ctimeFinished = ctimeFinished;
    }
}