package com.enjoylearning.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_business_recharge
 */
public class EbBusinessRecharge extends BaseEntity {
    /**
     * Database Column Remarks:
     *   文章分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_business_recharge.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   充值单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_business_recharge.out_trade_no
     *
     * @mbg.generated
     */
    private String outTradeNo;

    /**
     * Database Column Remarks:
     *   随机字符
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_business_recharge.nonce_str
     *
     * @mbg.generated
     */
    private String nonceStr;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_business_recharge.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * Database Column Remarks:
     *   状态:1已回调、0未回调
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_business_recharge.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   1删除0未删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_business_recharge.is_del
     *
     * @mbg.generated
     */
    private Boolean isDel;

    /**
     * Database Column Remarks:
     *   添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_business_recharge.add_time
     *
     * @mbg.generated
     */
    private String addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_business_recharge.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_business_recharge.id
     *
     * @return the value of eb_business_recharge.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_business_recharge.id
     *
     * @param id the value for eb_business_recharge.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_business_recharge.out_trade_no
     *
     * @return the value of eb_business_recharge.out_trade_no
     *
     * @mbg.generated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_business_recharge.out_trade_no
     *
     * @param outTradeNo the value for eb_business_recharge.out_trade_no
     *
     * @mbg.generated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_business_recharge.nonce_str
     *
     * @return the value of eb_business_recharge.nonce_str
     *
     * @mbg.generated
     */
    public String getNonceStr() {
        return nonceStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_business_recharge.nonce_str
     *
     * @param nonceStr the value for eb_business_recharge.nonce_str
     *
     * @mbg.generated
     */
    public void setNonceStr(String nonceStr) {
        this.nonceStr = nonceStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_business_recharge.note
     *
     * @return the value of eb_business_recharge.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_business_recharge.note
     *
     * @param note the value for eb_business_recharge.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_business_recharge.status
     *
     * @return the value of eb_business_recharge.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_business_recharge.status
     *
     * @param status the value for eb_business_recharge.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_business_recharge.is_del
     *
     * @return the value of eb_business_recharge.is_del
     *
     * @mbg.generated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_business_recharge.is_del
     *
     * @param isDel the value for eb_business_recharge.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_business_recharge.add_time
     *
     * @return the value of eb_business_recharge.add_time
     *
     * @mbg.generated
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_business_recharge.add_time
     *
     * @param addTime the value for eb_business_recharge.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_business_recharge.ctime
     *
     * @return the value of eb_business_recharge.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_business_recharge.ctime
     *
     * @param ctime the value for eb_business_recharge.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}