package com.enjoylearning.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_extract_protocol
 */
public class EbExtractProtocol extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_extract_protocol.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_extract_protocol.member_id
     *
     * @mbg.generated
     */
    private Integer memberId;

    /**
     * Database Column Remarks:
     *   yidangjia
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_extract_protocol.mer_str
     *
     * @mbg.generated
     */
    private String merStr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_extract_protocol.is_protocol
     *
     * @mbg.generated
     */
    private Byte isProtocol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_extract_protocol.insert_time
     *
     * @mbg.generated
     */
    private Date insertTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_extract_protocol.id
     *
     * @return the value of eb_extract_protocol.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_extract_protocol.id
     *
     * @param id the value for eb_extract_protocol.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_extract_protocol.member_id
     *
     * @return the value of eb_extract_protocol.member_id
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_extract_protocol.member_id
     *
     * @param memberId the value for eb_extract_protocol.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_extract_protocol.mer_str
     *
     * @return the value of eb_extract_protocol.mer_str
     *
     * @mbg.generated
     */
    public String getMerStr() {
        return merStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_extract_protocol.mer_str
     *
     * @param merStr the value for eb_extract_protocol.mer_str
     *
     * @mbg.generated
     */
    public void setMerStr(String merStr) {
        this.merStr = merStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_extract_protocol.is_protocol
     *
     * @return the value of eb_extract_protocol.is_protocol
     *
     * @mbg.generated
     */
    public Byte getIsProtocol() {
        return isProtocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_extract_protocol.is_protocol
     *
     * @param isProtocol the value for eb_extract_protocol.is_protocol
     *
     * @mbg.generated
     */
    public void setIsProtocol(Byte isProtocol) {
        this.isProtocol = isProtocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_extract_protocol.insert_time
     *
     * @return the value of eb_extract_protocol.insert_time
     *
     * @mbg.generated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_extract_protocol.insert_time
     *
     * @param insertTime the value for eb_extract_protocol.insert_time
     *
     * @mbg.generated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
}