package com.enjoylearning.mybatis.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_mer_extract
 */
public class EbMerExtract extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_mer_extract.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   提现的商户mer_id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_mer_extract.mer_id
     *
     * @mbg.generated
     */
    private Integer merId;

    /**
     * Database Column Remarks:
     *   提现申请人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_mer_extract.apply_man
     *
     * @mbg.generated
     */
    private String applyMan;

    /**
     * Database Column Remarks:
     *   交易流水号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_mer_extract.trans_number
     *
     * @mbg.generated
     */
    private String transNumber;

    /**
     * Database Column Remarks:
     *   申请提现的金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_mer_extract.apply_price
     *
     * @mbg.generated
     */
    private BigDecimal applyPrice;

    /**
     * Database Column Remarks:
     *   0 申请提现中 1 已提现 2 拒绝提现
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_mer_extract.apply_status
     *
     * @mbg.generated
     */
    private Boolean applyStatus;

    /**
     * Database Column Remarks:
     *   开户名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_mer_extract.account_name
     *
     * @mbg.generated
     */
    private String accountName;

    /**
     * Database Column Remarks:
     *   开户银行
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_mer_extract.account_bank
     *
     * @mbg.generated
     */
    private String accountBank;

    /**
     * Database Column Remarks:
     *   银行账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_mer_extract.account_no
     *
     * @mbg.generated
     */
    private String accountNo;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_mer_extract.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * Database Column Remarks:
     *   申请提现拒绝原因
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_mer_extract.refuse_reason
     *
     * @mbg.generated
     */
    private String refuseReason;

    /**
     * Database Column Remarks:
     *   申请提现拒绝时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_mer_extract.refuse_time
     *
     * @mbg.generated
     */
    private Date refuseTime;

    /**
     * Database Column Remarks:
     *   申请提现时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_mer_extract.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_mer_extract.id
     *
     * @return the value of eb_mer_extract.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_mer_extract.id
     *
     * @param id the value for eb_mer_extract.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_mer_extract.mer_id
     *
     * @return the value of eb_mer_extract.mer_id
     *
     * @mbg.generated
     */
    public Integer getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_mer_extract.mer_id
     *
     * @param merId the value for eb_mer_extract.mer_id
     *
     * @mbg.generated
     */
    public void setMerId(Integer merId) {
        this.merId = merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_mer_extract.apply_man
     *
     * @return the value of eb_mer_extract.apply_man
     *
     * @mbg.generated
     */
    public String getApplyMan() {
        return applyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_mer_extract.apply_man
     *
     * @param applyMan the value for eb_mer_extract.apply_man
     *
     * @mbg.generated
     */
    public void setApplyMan(String applyMan) {
        this.applyMan = applyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_mer_extract.trans_number
     *
     * @return the value of eb_mer_extract.trans_number
     *
     * @mbg.generated
     */
    public String getTransNumber() {
        return transNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_mer_extract.trans_number
     *
     * @param transNumber the value for eb_mer_extract.trans_number
     *
     * @mbg.generated
     */
    public void setTransNumber(String transNumber) {
        this.transNumber = transNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_mer_extract.apply_price
     *
     * @return the value of eb_mer_extract.apply_price
     *
     * @mbg.generated
     */
    public BigDecimal getApplyPrice() {
        return applyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_mer_extract.apply_price
     *
     * @param applyPrice the value for eb_mer_extract.apply_price
     *
     * @mbg.generated
     */
    public void setApplyPrice(BigDecimal applyPrice) {
        this.applyPrice = applyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_mer_extract.apply_status
     *
     * @return the value of eb_mer_extract.apply_status
     *
     * @mbg.generated
     */
    public Boolean getApplyStatus() {
        return applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_mer_extract.apply_status
     *
     * @param applyStatus the value for eb_mer_extract.apply_status
     *
     * @mbg.generated
     */
    public void setApplyStatus(Boolean applyStatus) {
        this.applyStatus = applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_mer_extract.account_name
     *
     * @return the value of eb_mer_extract.account_name
     *
     * @mbg.generated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_mer_extract.account_name
     *
     * @param accountName the value for eb_mer_extract.account_name
     *
     * @mbg.generated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_mer_extract.account_bank
     *
     * @return the value of eb_mer_extract.account_bank
     *
     * @mbg.generated
     */
    public String getAccountBank() {
        return accountBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_mer_extract.account_bank
     *
     * @param accountBank the value for eb_mer_extract.account_bank
     *
     * @mbg.generated
     */
    public void setAccountBank(String accountBank) {
        this.accountBank = accountBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_mer_extract.account_no
     *
     * @return the value of eb_mer_extract.account_no
     *
     * @mbg.generated
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_mer_extract.account_no
     *
     * @param accountNo the value for eb_mer_extract.account_no
     *
     * @mbg.generated
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_mer_extract.comment
     *
     * @return the value of eb_mer_extract.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_mer_extract.comment
     *
     * @param comment the value for eb_mer_extract.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_mer_extract.refuse_reason
     *
     * @return the value of eb_mer_extract.refuse_reason
     *
     * @mbg.generated
     */
    public String getRefuseReason() {
        return refuseReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_mer_extract.refuse_reason
     *
     * @param refuseReason the value for eb_mer_extract.refuse_reason
     *
     * @mbg.generated
     */
    public void setRefuseReason(String refuseReason) {
        this.refuseReason = refuseReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_mer_extract.refuse_time
     *
     * @return the value of eb_mer_extract.refuse_time
     *
     * @mbg.generated
     */
    public Date getRefuseTime() {
        return refuseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_mer_extract.refuse_time
     *
     * @param refuseTime the value for eb_mer_extract.refuse_time
     *
     * @mbg.generated
     */
    public void setRefuseTime(Date refuseTime) {
        this.refuseTime = refuseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_mer_extract.ctime
     *
     * @return the value of eb_mer_extract.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_mer_extract.ctime
     *
     * @param ctime the value for eb_mer_extract.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}