package com.enjoylearning.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_routine_qrcode
 */
public class EbRoutineQrcode extends BaseEntity {
    /**
     * Database Column Remarks:
     *   微信二维码ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_qrcode.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   二维码类型 spread(用户推广) product_spread(产品推广)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_qrcode.third_type
     *
     * @mbg.generated
     */
    private String thirdType;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_qrcode.third_id
     *
     * @mbg.generated
     */
    private Integer thirdId;

    /**
     * Database Column Remarks:
     *   状态 0不可用 1可用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_qrcode.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_qrcode.add_time
     *
     * @mbg.generated
     */
    private String addTime;

    /**
     * Database Column Remarks:
     *   小程序页面路径带参数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_qrcode.page
     *
     * @mbg.generated
     */
    private String page;

    /**
     * Database Column Remarks:
     *   小程序二维码路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_qrcode.qrcode_url
     *
     * @mbg.generated
     */
    private String qrcodeUrl;

    /**
     * Database Column Remarks:
     *   二维码添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_qrcode.url_time
     *
     * @mbg.generated
     */
    private Integer urlTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_qrcode.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_qrcode.id
     *
     * @return the value of eb_routine_qrcode.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_qrcode.id
     *
     * @param id the value for eb_routine_qrcode.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_qrcode.third_type
     *
     * @return the value of eb_routine_qrcode.third_type
     *
     * @mbg.generated
     */
    public String getThirdType() {
        return thirdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_qrcode.third_type
     *
     * @param thirdType the value for eb_routine_qrcode.third_type
     *
     * @mbg.generated
     */
    public void setThirdType(String thirdType) {
        this.thirdType = thirdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_qrcode.third_id
     *
     * @return the value of eb_routine_qrcode.third_id
     *
     * @mbg.generated
     */
    public Integer getThirdId() {
        return thirdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_qrcode.third_id
     *
     * @param thirdId the value for eb_routine_qrcode.third_id
     *
     * @mbg.generated
     */
    public void setThirdId(Integer thirdId) {
        this.thirdId = thirdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_qrcode.status
     *
     * @return the value of eb_routine_qrcode.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_qrcode.status
     *
     * @param status the value for eb_routine_qrcode.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_qrcode.add_time
     *
     * @return the value of eb_routine_qrcode.add_time
     *
     * @mbg.generated
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_qrcode.add_time
     *
     * @param addTime the value for eb_routine_qrcode.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_qrcode.page
     *
     * @return the value of eb_routine_qrcode.page
     *
     * @mbg.generated
     */
    public String getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_qrcode.page
     *
     * @param page the value for eb_routine_qrcode.page
     *
     * @mbg.generated
     */
    public void setPage(String page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_qrcode.qrcode_url
     *
     * @return the value of eb_routine_qrcode.qrcode_url
     *
     * @mbg.generated
     */
    public String getQrcodeUrl() {
        return qrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_qrcode.qrcode_url
     *
     * @param qrcodeUrl the value for eb_routine_qrcode.qrcode_url
     *
     * @mbg.generated
     */
    public void setQrcodeUrl(String qrcodeUrl) {
        this.qrcodeUrl = qrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_qrcode.url_time
     *
     * @return the value of eb_routine_qrcode.url_time
     *
     * @mbg.generated
     */
    public Integer getUrlTime() {
        return urlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_qrcode.url_time
     *
     * @param urlTime the value for eb_routine_qrcode.url_time
     *
     * @mbg.generated
     */
    public void setUrlTime(Integer urlTime) {
        this.urlTime = urlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_qrcode.ctime
     *
     * @return the value of eb_routine_qrcode.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_qrcode.ctime
     *
     * @param ctime the value for eb_routine_qrcode.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}