package com.enjoylearning.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_routine_access_token
 */
public class EbRoutineAccessToken extends BaseEntity {
    /**
     * Database Column Remarks:
     *   小程序access_token表ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_access_token.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   openid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_access_token.access_token
     *
     * @mbg.generated
     */
    private String accessToken;

    /**
     * Database Column Remarks:
     *   添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_access_token.stop_time
     *
     * @mbg.generated
     */
    private Integer stopTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_access_token.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_access_token.id
     *
     * @return the value of eb_routine_access_token.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_access_token.id
     *
     * @param id the value for eb_routine_access_token.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_access_token.access_token
     *
     * @return the value of eb_routine_access_token.access_token
     *
     * @mbg.generated
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_access_token.access_token
     *
     * @param accessToken the value for eb_routine_access_token.access_token
     *
     * @mbg.generated
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_access_token.stop_time
     *
     * @return the value of eb_routine_access_token.stop_time
     *
     * @mbg.generated
     */
    public Integer getStopTime() {
        return stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_access_token.stop_time
     *
     * @param stopTime the value for eb_routine_access_token.stop_time
     *
     * @mbg.generated
     */
    public void setStopTime(Integer stopTime) {
        this.stopTime = stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_access_token.ctime
     *
     * @return the value of eb_routine_access_token.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_access_token.ctime
     *
     * @param ctime the value for eb_routine_access_token.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}