package com.enjoylearning.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_routine_form_id
 */
public class EbRoutineFormId extends BaseEntity {
    /**
     * Database Column Remarks:
     *   表单ID表ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_form_id.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户uid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_form_id.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   表单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_form_id.form_id
     *
     * @mbg.generated
     */
    private String formId;

    /**
     * Database Column Remarks:
     *   表单ID失效时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_form_id.stop_time
     *
     * @mbg.generated
     */
    private Integer stopTime;

    /**
     * Database Column Remarks:
     *   状态1 未使用 2不能使用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_form_id.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_routine_form_id.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_form_id.id
     *
     * @return the value of eb_routine_form_id.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_form_id.id
     *
     * @param id the value for eb_routine_form_id.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_form_id.uid
     *
     * @return the value of eb_routine_form_id.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_form_id.uid
     *
     * @param uid the value for eb_routine_form_id.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_form_id.form_id
     *
     * @return the value of eb_routine_form_id.form_id
     *
     * @mbg.generated
     */
    public String getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_form_id.form_id
     *
     * @param formId the value for eb_routine_form_id.form_id
     *
     * @mbg.generated
     */
    public void setFormId(String formId) {
        this.formId = formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_form_id.stop_time
     *
     * @return the value of eb_routine_form_id.stop_time
     *
     * @mbg.generated
     */
    public Integer getStopTime() {
        return stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_form_id.stop_time
     *
     * @param stopTime the value for eb_routine_form_id.stop_time
     *
     * @mbg.generated
     */
    public void setStopTime(Integer stopTime) {
        this.stopTime = stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_form_id.status
     *
     * @return the value of eb_routine_form_id.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_form_id.status
     *
     * @param status the value for eb_routine_form_id.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_routine_form_id.ctime
     *
     * @return the value of eb_routine_form_id.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_routine_form_id.ctime
     *
     * @param ctime the value for eb_routine_form_id.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}