package com.enjoylearning.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_store_coupon_issue
 */
public class EbStoreCouponIssue extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_coupon_issue.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   优惠券ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_coupon_issue.cid
     *
     * @mbg.generated
     */
    private Integer cid;

    /**
     * Database Column Remarks:
     *   优惠券领取开启时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_coupon_issue.start_time
     *
     * @mbg.generated
     */
    private Integer startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_coupon_issue.stime
     *
     * @mbg.generated
     */
    private Date stime;

    /**
     * Database Column Remarks:
     *   优惠券领取结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_coupon_issue.end_time
     *
     * @mbg.generated
     */
    private Integer endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_coupon_issue.etime
     *
     * @mbg.generated
     */
    private Date etime;

    /**
     * Database Column Remarks:
     *   优惠券领取数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_coupon_issue.total_count
     *
     * @mbg.generated
     */
    private Integer totalCount;

    /**
     * Database Column Remarks:
     *   优惠券剩余领取数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_coupon_issue.remain_count
     *
     * @mbg.generated
     */
    private Integer remainCount;

    /**
     * Database Column Remarks:
     *   是否无限张数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_coupon_issue.is_permanent
     *
     * @mbg.generated
     */
    private Boolean isPermanent;

    /**
     * Database Column Remarks:
     *   1 正常 0 未开启 -1 已无效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_coupon_issue.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_coupon_issue.is_del
     *
     * @mbg.generated
     */
    private Boolean isDel;

    /**
     * Database Column Remarks:
     *   优惠券添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_coupon_issue.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_coupon_issue.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_coupon_issue.id
     *
     * @return the value of eb_store_coupon_issue.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_coupon_issue.id
     *
     * @param id the value for eb_store_coupon_issue.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_coupon_issue.cid
     *
     * @return the value of eb_store_coupon_issue.cid
     *
     * @mbg.generated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_coupon_issue.cid
     *
     * @param cid the value for eb_store_coupon_issue.cid
     *
     * @mbg.generated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_coupon_issue.start_time
     *
     * @return the value of eb_store_coupon_issue.start_time
     *
     * @mbg.generated
     */
    public Integer getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_coupon_issue.start_time
     *
     * @param startTime the value for eb_store_coupon_issue.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Integer startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_coupon_issue.stime
     *
     * @return the value of eb_store_coupon_issue.stime
     *
     * @mbg.generated
     */
    public Date getStime() {
        return stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_coupon_issue.stime
     *
     * @param stime the value for eb_store_coupon_issue.stime
     *
     * @mbg.generated
     */
    public void setStime(Date stime) {
        this.stime = stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_coupon_issue.end_time
     *
     * @return the value of eb_store_coupon_issue.end_time
     *
     * @mbg.generated
     */
    public Integer getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_coupon_issue.end_time
     *
     * @param endTime the value for eb_store_coupon_issue.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Integer endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_coupon_issue.etime
     *
     * @return the value of eb_store_coupon_issue.etime
     *
     * @mbg.generated
     */
    public Date getEtime() {
        return etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_coupon_issue.etime
     *
     * @param etime the value for eb_store_coupon_issue.etime
     *
     * @mbg.generated
     */
    public void setEtime(Date etime) {
        this.etime = etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_coupon_issue.total_count
     *
     * @return the value of eb_store_coupon_issue.total_count
     *
     * @mbg.generated
     */
    public Integer getTotalCount() {
        return totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_coupon_issue.total_count
     *
     * @param totalCount the value for eb_store_coupon_issue.total_count
     *
     * @mbg.generated
     */
    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_coupon_issue.remain_count
     *
     * @return the value of eb_store_coupon_issue.remain_count
     *
     * @mbg.generated
     */
    public Integer getRemainCount() {
        return remainCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_coupon_issue.remain_count
     *
     * @param remainCount the value for eb_store_coupon_issue.remain_count
     *
     * @mbg.generated
     */
    public void setRemainCount(Integer remainCount) {
        this.remainCount = remainCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_coupon_issue.is_permanent
     *
     * @return the value of eb_store_coupon_issue.is_permanent
     *
     * @mbg.generated
     */
    public Boolean getIsPermanent() {
        return isPermanent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_coupon_issue.is_permanent
     *
     * @param isPermanent the value for eb_store_coupon_issue.is_permanent
     *
     * @mbg.generated
     */
    public void setIsPermanent(Boolean isPermanent) {
        this.isPermanent = isPermanent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_coupon_issue.status
     *
     * @return the value of eb_store_coupon_issue.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_coupon_issue.status
     *
     * @param status the value for eb_store_coupon_issue.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_coupon_issue.is_del
     *
     * @return the value of eb_store_coupon_issue.is_del
     *
     * @mbg.generated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_coupon_issue.is_del
     *
     * @param isDel the value for eb_store_coupon_issue.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_coupon_issue.add_time
     *
     * @return the value of eb_store_coupon_issue.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_coupon_issue.add_time
     *
     * @param addTime the value for eb_store_coupon_issue.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_coupon_issue.ctime
     *
     * @return the value of eb_store_coupon_issue.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_coupon_issue.ctime
     *
     * @param ctime the value for eb_store_coupon_issue.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}