package com.enjoylearning.mybatis.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_store_bargain_user
 */
public class EbStoreBargainUser extends BaseEntity {
    /**
     * Database Column Remarks:
     *   用户参与砍价表ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_bargain_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_bargain_user.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   砍价产品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_bargain_user.bargain_id
     *
     * @mbg.generated
     */
    private Integer bargainId;

    /**
     * Database Column Remarks:
     *   砍价的最低价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_bargain_user.bargain_price_min
     *
     * @mbg.generated
     */
    private BigDecimal bargainPriceMin;

    /**
     * Database Column Remarks:
     *   砍价金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_bargain_user.bargain_price
     *
     * @mbg.generated
     */
    private BigDecimal bargainPrice;

    /**
     * Database Column Remarks:
     *   砍掉的价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_bargain_user.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   状态 1参与中 2 活动结束参与失败 3活动结束参与成功
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_bargain_user.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   参与时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_bargain_user.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     * Database Column Remarks:
     *   是否取消
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_bargain_user.is_del
     *
     * @mbg.generated
     */
    private Boolean isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_bargain_user.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_bargain_user.id
     *
     * @return the value of eb_store_bargain_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_bargain_user.id
     *
     * @param id the value for eb_store_bargain_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_bargain_user.uid
     *
     * @return the value of eb_store_bargain_user.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_bargain_user.uid
     *
     * @param uid the value for eb_store_bargain_user.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_bargain_user.bargain_id
     *
     * @return the value of eb_store_bargain_user.bargain_id
     *
     * @mbg.generated
     */
    public Integer getBargainId() {
        return bargainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_bargain_user.bargain_id
     *
     * @param bargainId the value for eb_store_bargain_user.bargain_id
     *
     * @mbg.generated
     */
    public void setBargainId(Integer bargainId) {
        this.bargainId = bargainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_bargain_user.bargain_price_min
     *
     * @return the value of eb_store_bargain_user.bargain_price_min
     *
     * @mbg.generated
     */
    public BigDecimal getBargainPriceMin() {
        return bargainPriceMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_bargain_user.bargain_price_min
     *
     * @param bargainPriceMin the value for eb_store_bargain_user.bargain_price_min
     *
     * @mbg.generated
     */
    public void setBargainPriceMin(BigDecimal bargainPriceMin) {
        this.bargainPriceMin = bargainPriceMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_bargain_user.bargain_price
     *
     * @return the value of eb_store_bargain_user.bargain_price
     *
     * @mbg.generated
     */
    public BigDecimal getBargainPrice() {
        return bargainPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_bargain_user.bargain_price
     *
     * @param bargainPrice the value for eb_store_bargain_user.bargain_price
     *
     * @mbg.generated
     */
    public void setBargainPrice(BigDecimal bargainPrice) {
        this.bargainPrice = bargainPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_bargain_user.price
     *
     * @return the value of eb_store_bargain_user.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_bargain_user.price
     *
     * @param price the value for eb_store_bargain_user.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_bargain_user.status
     *
     * @return the value of eb_store_bargain_user.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_bargain_user.status
     *
     * @param status the value for eb_store_bargain_user.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_bargain_user.add_time
     *
     * @return the value of eb_store_bargain_user.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_bargain_user.add_time
     *
     * @param addTime the value for eb_store_bargain_user.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_bargain_user.is_del
     *
     * @return the value of eb_store_bargain_user.is_del
     *
     * @mbg.generated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_bargain_user.is_del
     *
     * @param isDel the value for eb_store_bargain_user.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_bargain_user.ctime
     *
     * @return the value of eb_store_bargain_user.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_bargain_user.ctime
     *
     * @param ctime the value for eb_store_bargain_user.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}