package com.enjoylearning.mybatis.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_store_product
 */
public class EbStoreProduct extends BaseEntity {
    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   商户Id(0为总后台管理员创建,不为0的时候是商户后台创建)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.mer_id
     *
     * @mbg.generated
     */
    private Integer merId;

    /**
     * Database Column Remarks:
     *   微商商户里的商品ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.origin_id
     *
     * @mbg.generated
     */
    private Integer originId;

    /**
     * Database Column Remarks:
     *   商品图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.image
     *
     * @mbg.generated
     */
    private String image;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.store_name
     *
     * @mbg.generated
     */
    private String storeName;

    /**
     * Database Column Remarks:
     *   商品简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.store_info
     *
     * @mbg.generated
     */
    private String storeInfo;

    /**
     * Database Column Remarks:
     *   关键字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.keyword
     *
     * @mbg.generated
     */
    private String keyword;

    /**
     * Database Column Remarks:
     *   分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.cate_id
     *
     * @mbg.generated
     */
    private String cateId;

    /**
     * Database Column Remarks:
     *   商品价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   会员价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.vip_price
     *
     * @mbg.generated
     */
    private BigDecimal vipPrice;

    /**
     * Database Column Remarks:
     *   市场价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.ot_price
     *
     * @mbg.generated
     */
    private BigDecimal otPrice;

    /**
     * Database Column Remarks:
     *   邮费
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.postage
     *
     * @mbg.generated
     */
    private BigDecimal postage;

    /**
     * Database Column Remarks:
     *   单位名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.unit_name
     *
     * @mbg.generated
     */
    private String unitName;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.sort
     *
     * @mbg.generated
     */
    private Short sort;

    /**
     * Database Column Remarks:
     *   销量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.sales
     *
     * @mbg.generated
     */
    private Integer sales;

    /**
     * Database Column Remarks:
     *   库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.stock
     *
     * @mbg.generated
     */
    private Integer stock;

    /**
     * Database Column Remarks:
     *   上架时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.sale_from
     *
     * @mbg.generated
     */
    private Date saleFrom;

    /**
     * Database Column Remarks:
     *   下架时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.sale_to
     *
     * @mbg.generated
     */
    private Date saleTo;

    /**
     * Database Column Remarks:
     *   状态（0：未上架，1：上架）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_show
     *
     * @mbg.generated
     */
    private Boolean isShow;

    /**
     * Database Column Remarks:
     *   是否热卖
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_hot
     *
     * @mbg.generated
     */
    private Boolean isHot;

    /**
     * Database Column Remarks:
     *   是否优惠
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_benefit
     *
     * @mbg.generated
     */
    private Boolean isBenefit;

    /**
     * Database Column Remarks:
     *   是否精品
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_best
     *
     * @mbg.generated
     */
    private Boolean isBest;

    /**
     * Database Column Remarks:
     *   是否新品
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_new
     *
     * @mbg.generated
     */
    private Boolean isNew;

    /**
     * Database Column Remarks:
     *   添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     * Database Column Remarks:
     *   是否包邮
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_postage
     *
     * @mbg.generated
     */
    private Boolean isPostage;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_del
     *
     * @mbg.generated
     */
    private Boolean isDel;

    /**
     * Database Column Remarks:
     *   商户是否代理 0不可代理1可代理
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.mer_use
     *
     * @mbg.generated
     */
    private Boolean merUse;

    /**
     * Database Column Remarks:
     *   获得积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.give_integral
     *
     * @mbg.generated
     */
    private BigDecimal giveIntegral;

    /**
     * Database Column Remarks:
     *   供方成本价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.source_cost
     *
     * @mbg.generated
     */
    private BigDecimal sourceCost;

    /**
     * Database Column Remarks:
     *   成本价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.cost
     *
     * @mbg.generated
     */
    private BigDecimal cost;

    /**
     * Database Column Remarks:
     *   秒杀状态 0 未开启 1已开启
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_seckill
     *
     * @mbg.generated
     */
    private Boolean isSeckill;

    /**
     * Database Column Remarks:
     *   砍价状态 0未开启 1开启
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_bargain
     *
     * @mbg.generated
     */
    private Boolean isBargain;

    /**
     * Database Column Remarks:
     *   虚拟销量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.ficti
     *
     * @mbg.generated
     */
    private Integer ficti;

    /**
     * Database Column Remarks:
     *   浏览量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.browse
     *
     * @mbg.generated
     */
    private Integer browse;

    /**
     * Database Column Remarks:
     *   产品二维码地址(用户小程序海报)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.code_path
     *
     * @mbg.generated
     */
    private String codePath;

    /**
     * Database Column Remarks:
     *   产品编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.store_code
     *
     * @mbg.generated
     */
    private String storeCode;

    /**
     * Database Column Remarks:
     *   淘宝、天猫、1688商品保存标识，避免商品重复入库
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.soure_link
     *
     * @mbg.generated
     */
    private String soureLink;

    /**
     * Database Column Remarks:
     *   品牌id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.brand
     *
     * @mbg.generated
     */
    private Integer brand;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * Database Column Remarks:
     *   小当家商品ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.goodsid_xdj
     *
     * @mbg.generated
     */
    private Integer goodsidXdj;

    /**
     * Database Column Remarks:
     *   小当家商品上次更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.last_update_xdj
     *
     * @mbg.generated
     */
    private Date lastUpdateXdj;

    /**
     * Database Column Remarks:
     *   轮播图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.slider_image
     *
     * @mbg.generated
     */
    private String sliderImage;

    /**
     * Database Column Remarks:
     *   供方发来的等级价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.ori_level_prices
     *
     * @mbg.generated
     */
    private String oriLevelPrices;

    /**
     * Database Column Remarks:
     *   等级价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.level_prices
     *
     * @mbg.generated
     */
    private String levelPrices;

    /**
     * Database Column Remarks:
     *   产品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   小当家不可配送地区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.forbbiden_area
     *
     * @mbg.generated
     */
    private String forbbidenArea;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.id
     *
     * @return the value of eb_store_product.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.id
     *
     * @param id the value for eb_store_product.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.mer_id
     *
     * @return the value of eb_store_product.mer_id
     *
     * @mbg.generated
     */
    public Integer getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.mer_id
     *
     * @param merId the value for eb_store_product.mer_id
     *
     * @mbg.generated
     */
    public void setMerId(Integer merId) {
        this.merId = merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.origin_id
     *
     * @return the value of eb_store_product.origin_id
     *
     * @mbg.generated
     */
    public Integer getOriginId() {
        return originId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.origin_id
     *
     * @param originId the value for eb_store_product.origin_id
     *
     * @mbg.generated
     */
    public void setOriginId(Integer originId) {
        this.originId = originId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.image
     *
     * @return the value of eb_store_product.image
     *
     * @mbg.generated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.image
     *
     * @param image the value for eb_store_product.image
     *
     * @mbg.generated
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.store_name
     *
     * @return the value of eb_store_product.store_name
     *
     * @mbg.generated
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.store_name
     *
     * @param storeName the value for eb_store_product.store_name
     *
     * @mbg.generated
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.store_info
     *
     * @return the value of eb_store_product.store_info
     *
     * @mbg.generated
     */
    public String getStoreInfo() {
        return storeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.store_info
     *
     * @param storeInfo the value for eb_store_product.store_info
     *
     * @mbg.generated
     */
    public void setStoreInfo(String storeInfo) {
        this.storeInfo = storeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.keyword
     *
     * @return the value of eb_store_product.keyword
     *
     * @mbg.generated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.keyword
     *
     * @param keyword the value for eb_store_product.keyword
     *
     * @mbg.generated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.cate_id
     *
     * @return the value of eb_store_product.cate_id
     *
     * @mbg.generated
     */
    public String getCateId() {
        return cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.cate_id
     *
     * @param cateId the value for eb_store_product.cate_id
     *
     * @mbg.generated
     */
    public void setCateId(String cateId) {
        this.cateId = cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.price
     *
     * @return the value of eb_store_product.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.price
     *
     * @param price the value for eb_store_product.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.vip_price
     *
     * @return the value of eb_store_product.vip_price
     *
     * @mbg.generated
     */
    public BigDecimal getVipPrice() {
        return vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.vip_price
     *
     * @param vipPrice the value for eb_store_product.vip_price
     *
     * @mbg.generated
     */
    public void setVipPrice(BigDecimal vipPrice) {
        this.vipPrice = vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.ot_price
     *
     * @return the value of eb_store_product.ot_price
     *
     * @mbg.generated
     */
    public BigDecimal getOtPrice() {
        return otPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.ot_price
     *
     * @param otPrice the value for eb_store_product.ot_price
     *
     * @mbg.generated
     */
    public void setOtPrice(BigDecimal otPrice) {
        this.otPrice = otPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.postage
     *
     * @return the value of eb_store_product.postage
     *
     * @mbg.generated
     */
    public BigDecimal getPostage() {
        return postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.postage
     *
     * @param postage the value for eb_store_product.postage
     *
     * @mbg.generated
     */
    public void setPostage(BigDecimal postage) {
        this.postage = postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.unit_name
     *
     * @return the value of eb_store_product.unit_name
     *
     * @mbg.generated
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.unit_name
     *
     * @param unitName the value for eb_store_product.unit_name
     *
     * @mbg.generated
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.sort
     *
     * @return the value of eb_store_product.sort
     *
     * @mbg.generated
     */
    public Short getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.sort
     *
     * @param sort the value for eb_store_product.sort
     *
     * @mbg.generated
     */
    public void setSort(Short sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.sales
     *
     * @return the value of eb_store_product.sales
     *
     * @mbg.generated
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.sales
     *
     * @param sales the value for eb_store_product.sales
     *
     * @mbg.generated
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.stock
     *
     * @return the value of eb_store_product.stock
     *
     * @mbg.generated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.stock
     *
     * @param stock the value for eb_store_product.stock
     *
     * @mbg.generated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.sale_from
     *
     * @return the value of eb_store_product.sale_from
     *
     * @mbg.generated
     */
    public Date getSaleFrom() {
        return saleFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.sale_from
     *
     * @param saleFrom the value for eb_store_product.sale_from
     *
     * @mbg.generated
     */
    public void setSaleFrom(Date saleFrom) {
        this.saleFrom = saleFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.sale_to
     *
     * @return the value of eb_store_product.sale_to
     *
     * @mbg.generated
     */
    public Date getSaleTo() {
        return saleTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.sale_to
     *
     * @param saleTo the value for eb_store_product.sale_to
     *
     * @mbg.generated
     */
    public void setSaleTo(Date saleTo) {
        this.saleTo = saleTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_show
     *
     * @return the value of eb_store_product.is_show
     *
     * @mbg.generated
     */
    public Boolean getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_show
     *
     * @param isShow the value for eb_store_product.is_show
     *
     * @mbg.generated
     */
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_hot
     *
     * @return the value of eb_store_product.is_hot
     *
     * @mbg.generated
     */
    public Boolean getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_hot
     *
     * @param isHot the value for eb_store_product.is_hot
     *
     * @mbg.generated
     */
    public void setIsHot(Boolean isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_benefit
     *
     * @return the value of eb_store_product.is_benefit
     *
     * @mbg.generated
     */
    public Boolean getIsBenefit() {
        return isBenefit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_benefit
     *
     * @param isBenefit the value for eb_store_product.is_benefit
     *
     * @mbg.generated
     */
    public void setIsBenefit(Boolean isBenefit) {
        this.isBenefit = isBenefit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_best
     *
     * @return the value of eb_store_product.is_best
     *
     * @mbg.generated
     */
    public Boolean getIsBest() {
        return isBest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_best
     *
     * @param isBest the value for eb_store_product.is_best
     *
     * @mbg.generated
     */
    public void setIsBest(Boolean isBest) {
        this.isBest = isBest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_new
     *
     * @return the value of eb_store_product.is_new
     *
     * @mbg.generated
     */
    public Boolean getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_new
     *
     * @param isNew the value for eb_store_product.is_new
     *
     * @mbg.generated
     */
    public void setIsNew(Boolean isNew) {
        this.isNew = isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.add_time
     *
     * @return the value of eb_store_product.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.add_time
     *
     * @param addTime the value for eb_store_product.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_postage
     *
     * @return the value of eb_store_product.is_postage
     *
     * @mbg.generated
     */
    public Boolean getIsPostage() {
        return isPostage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_postage
     *
     * @param isPostage the value for eb_store_product.is_postage
     *
     * @mbg.generated
     */
    public void setIsPostage(Boolean isPostage) {
        this.isPostage = isPostage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_del
     *
     * @return the value of eb_store_product.is_del
     *
     * @mbg.generated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_del
     *
     * @param isDel the value for eb_store_product.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.mer_use
     *
     * @return the value of eb_store_product.mer_use
     *
     * @mbg.generated
     */
    public Boolean getMerUse() {
        return merUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.mer_use
     *
     * @param merUse the value for eb_store_product.mer_use
     *
     * @mbg.generated
     */
    public void setMerUse(Boolean merUse) {
        this.merUse = merUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.give_integral
     *
     * @return the value of eb_store_product.give_integral
     *
     * @mbg.generated
     */
    public BigDecimal getGiveIntegral() {
        return giveIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.give_integral
     *
     * @param giveIntegral the value for eb_store_product.give_integral
     *
     * @mbg.generated
     */
    public void setGiveIntegral(BigDecimal giveIntegral) {
        this.giveIntegral = giveIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.source_cost
     *
     * @return the value of eb_store_product.source_cost
     *
     * @mbg.generated
     */
    public BigDecimal getSourceCost() {
        return sourceCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.source_cost
     *
     * @param sourceCost the value for eb_store_product.source_cost
     *
     * @mbg.generated
     */
    public void setSourceCost(BigDecimal sourceCost) {
        this.sourceCost = sourceCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.cost
     *
     * @return the value of eb_store_product.cost
     *
     * @mbg.generated
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.cost
     *
     * @param cost the value for eb_store_product.cost
     *
     * @mbg.generated
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_seckill
     *
     * @return the value of eb_store_product.is_seckill
     *
     * @mbg.generated
     */
    public Boolean getIsSeckill() {
        return isSeckill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_seckill
     *
     * @param isSeckill the value for eb_store_product.is_seckill
     *
     * @mbg.generated
     */
    public void setIsSeckill(Boolean isSeckill) {
        this.isSeckill = isSeckill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_bargain
     *
     * @return the value of eb_store_product.is_bargain
     *
     * @mbg.generated
     */
    public Boolean getIsBargain() {
        return isBargain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_bargain
     *
     * @param isBargain the value for eb_store_product.is_bargain
     *
     * @mbg.generated
     */
    public void setIsBargain(Boolean isBargain) {
        this.isBargain = isBargain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.ficti
     *
     * @return the value of eb_store_product.ficti
     *
     * @mbg.generated
     */
    public Integer getFicti() {
        return ficti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.ficti
     *
     * @param ficti the value for eb_store_product.ficti
     *
     * @mbg.generated
     */
    public void setFicti(Integer ficti) {
        this.ficti = ficti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.browse
     *
     * @return the value of eb_store_product.browse
     *
     * @mbg.generated
     */
    public Integer getBrowse() {
        return browse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.browse
     *
     * @param browse the value for eb_store_product.browse
     *
     * @mbg.generated
     */
    public void setBrowse(Integer browse) {
        this.browse = browse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.code_path
     *
     * @return the value of eb_store_product.code_path
     *
     * @mbg.generated
     */
    public String getCodePath() {
        return codePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.code_path
     *
     * @param codePath the value for eb_store_product.code_path
     *
     * @mbg.generated
     */
    public void setCodePath(String codePath) {
        this.codePath = codePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.store_code
     *
     * @return the value of eb_store_product.store_code
     *
     * @mbg.generated
     */
    public String getStoreCode() {
        return storeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.store_code
     *
     * @param storeCode the value for eb_store_product.store_code
     *
     * @mbg.generated
     */
    public void setStoreCode(String storeCode) {
        this.storeCode = storeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.soure_link
     *
     * @return the value of eb_store_product.soure_link
     *
     * @mbg.generated
     */
    public String getSoureLink() {
        return soureLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.soure_link
     *
     * @param soureLink the value for eb_store_product.soure_link
     *
     * @mbg.generated
     */
    public void setSoureLink(String soureLink) {
        this.soureLink = soureLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.brand
     *
     * @return the value of eb_store_product.brand
     *
     * @mbg.generated
     */
    public Integer getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.brand
     *
     * @param brand the value for eb_store_product.brand
     *
     * @mbg.generated
     */
    public void setBrand(Integer brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.ctime
     *
     * @return the value of eb_store_product.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.ctime
     *
     * @param ctime the value for eb_store_product.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.goodsid_xdj
     *
     * @return the value of eb_store_product.goodsid_xdj
     *
     * @mbg.generated
     */
    public Integer getGoodsidXdj() {
        return goodsidXdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.goodsid_xdj
     *
     * @param goodsidXdj the value for eb_store_product.goodsid_xdj
     *
     * @mbg.generated
     */
    public void setGoodsidXdj(Integer goodsidXdj) {
        this.goodsidXdj = goodsidXdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.last_update_xdj
     *
     * @return the value of eb_store_product.last_update_xdj
     *
     * @mbg.generated
     */
    public Date getLastUpdateXdj() {
        return lastUpdateXdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.last_update_xdj
     *
     * @param lastUpdateXdj the value for eb_store_product.last_update_xdj
     *
     * @mbg.generated
     */
    public void setLastUpdateXdj(Date lastUpdateXdj) {
        this.lastUpdateXdj = lastUpdateXdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.slider_image
     *
     * @return the value of eb_store_product.slider_image
     *
     * @mbg.generated
     */
    public String getSliderImage() {
        return sliderImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.slider_image
     *
     * @param sliderImage the value for eb_store_product.slider_image
     *
     * @mbg.generated
     */
    public void setSliderImage(String sliderImage) {
        this.sliderImage = sliderImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.ori_level_prices
     *
     * @return the value of eb_store_product.ori_level_prices
     *
     * @mbg.generated
     */
    public String getOriLevelPrices() {
        return oriLevelPrices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.ori_level_prices
     *
     * @param oriLevelPrices the value for eb_store_product.ori_level_prices
     *
     * @mbg.generated
     */
    public void setOriLevelPrices(String oriLevelPrices) {
        this.oriLevelPrices = oriLevelPrices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.level_prices
     *
     * @return the value of eb_store_product.level_prices
     *
     * @mbg.generated
     */
    public String getLevelPrices() {
        return levelPrices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.level_prices
     *
     * @param levelPrices the value for eb_store_product.level_prices
     *
     * @mbg.generated
     */
    public void setLevelPrices(String levelPrices) {
        this.levelPrices = levelPrices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.description
     *
     * @return the value of eb_store_product.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.description
     *
     * @param description the value for eb_store_product.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.forbbiden_area
     *
     * @return the value of eb_store_product.forbbiden_area
     *
     * @mbg.generated
     */
    public String getForbbidenArea() {
        return forbbidenArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.forbbiden_area
     *
     * @param forbbidenArea the value for eb_store_product.forbbiden_area
     *
     * @mbg.generated
     */
    public void setForbbidenArea(String forbbidenArea) {
        this.forbbidenArea = forbbidenArea;
    }
}