package com.enjoylearning.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_store_service
 */
public class EbStoreService extends BaseEntity {
    /**
     * Database Column Remarks:
     *   客服id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   商户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service.mer_id
     *
     * @mbg.generated
     */
    private Integer merId;

    /**
     * Database Column Remarks:
     *   客服uid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   客服头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     * Database Column Remarks:
     *   代理名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     * Database Column Remarks:
     *   添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     * Database Column Remarks:
     *   0隐藏1显示
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   订单通知1开启0关闭
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service.notify
     *
     * @mbg.generated
     */
    private Integer notify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service.id
     *
     * @return the value of eb_store_service.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service.id
     *
     * @param id the value for eb_store_service.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service.mer_id
     *
     * @return the value of eb_store_service.mer_id
     *
     * @mbg.generated
     */
    public Integer getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service.mer_id
     *
     * @param merId the value for eb_store_service.mer_id
     *
     * @mbg.generated
     */
    public void setMerId(Integer merId) {
        this.merId = merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service.uid
     *
     * @return the value of eb_store_service.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service.uid
     *
     * @param uid the value for eb_store_service.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service.avatar
     *
     * @return the value of eb_store_service.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service.avatar
     *
     * @param avatar the value for eb_store_service.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service.nickname
     *
     * @return the value of eb_store_service.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service.nickname
     *
     * @param nickname the value for eb_store_service.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service.add_time
     *
     * @return the value of eb_store_service.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service.add_time
     *
     * @param addTime the value for eb_store_service.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service.status
     *
     * @return the value of eb_store_service.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service.status
     *
     * @param status the value for eb_store_service.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service.notify
     *
     * @return the value of eb_store_service.notify
     *
     * @mbg.generated
     */
    public Integer getNotify() {
        return notify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service.notify
     *
     * @param notify the value for eb_store_service.notify
     *
     * @mbg.generated
     */
    public void setNotify(Integer notify) {
        this.notify = notify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service.ctime
     *
     * @return the value of eb_store_service.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service.ctime
     *
     * @param ctime the value for eb_store_service.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}