package com.enjoylearning.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_store_service_log
 */
public class EbStoreServiceLog extends BaseEntity {
    /**
     * Database Column Remarks:
     *   客服用户对话记录表ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   商户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service_log.mer_id
     *
     * @mbg.generated
     */
    private Integer merId;

    /**
     * Database Column Remarks:
     *   发送人uid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service_log.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   接收人uid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service_log.to_uid
     *
     * @mbg.generated
     */
    private Integer toUid;

    /**
     * Database Column Remarks:
     *   发送时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service_log.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     * Database Column Remarks:
     *   是否已读（0：否；1：是；）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service_log.type
     *
     * @mbg.generated
     */
    private Boolean type;

    /**
     * Database Column Remarks:
     *   是否提醒过
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service_log.remind
     *
     * @mbg.generated
     */
    private Boolean remind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service_log.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * Database Column Remarks:
     *   消息内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_service_log.msn
     *
     * @mbg.generated
     */
    private String msn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service_log.id
     *
     * @return the value of eb_store_service_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service_log.id
     *
     * @param id the value for eb_store_service_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service_log.mer_id
     *
     * @return the value of eb_store_service_log.mer_id
     *
     * @mbg.generated
     */
    public Integer getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service_log.mer_id
     *
     * @param merId the value for eb_store_service_log.mer_id
     *
     * @mbg.generated
     */
    public void setMerId(Integer merId) {
        this.merId = merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service_log.uid
     *
     * @return the value of eb_store_service_log.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service_log.uid
     *
     * @param uid the value for eb_store_service_log.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service_log.to_uid
     *
     * @return the value of eb_store_service_log.to_uid
     *
     * @mbg.generated
     */
    public Integer getToUid() {
        return toUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service_log.to_uid
     *
     * @param toUid the value for eb_store_service_log.to_uid
     *
     * @mbg.generated
     */
    public void setToUid(Integer toUid) {
        this.toUid = toUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service_log.add_time
     *
     * @return the value of eb_store_service_log.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service_log.add_time
     *
     * @param addTime the value for eb_store_service_log.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service_log.type
     *
     * @return the value of eb_store_service_log.type
     *
     * @mbg.generated
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service_log.type
     *
     * @param type the value for eb_store_service_log.type
     *
     * @mbg.generated
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service_log.remind
     *
     * @return the value of eb_store_service_log.remind
     *
     * @mbg.generated
     */
    public Boolean getRemind() {
        return remind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service_log.remind
     *
     * @param remind the value for eb_store_service_log.remind
     *
     * @mbg.generated
     */
    public void setRemind(Boolean remind) {
        this.remind = remind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service_log.ctime
     *
     * @return the value of eb_store_service_log.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service_log.ctime
     *
     * @param ctime the value for eb_store_service_log.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_service_log.msn
     *
     * @return the value of eb_store_service_log.msn
     *
     * @mbg.generated
     */
    public String getMsn() {
        return msn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_service_log.msn
     *
     * @param msn the value for eb_store_service_log.msn
     *
     * @mbg.generated
     */
    public void setMsn(String msn) {
        this.msn = msn;
    }
}