package com.enjoylearning.mybatis.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_store_order_cart_info
 */
public class EbStoreOrderCartInfo extends BaseEntity {
    /**
     * Database Column Remarks:
     *   订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_order_cart_info.oid
     *
     * @mbg.generated
     */
    private Integer oid;

    /**
     * Database Column Remarks:
     *   购物车id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_order_cart_info.cart_id
     *
     * @mbg.generated
     */
    private Integer cartId;

    /**
     * Database Column Remarks:
     *   商品ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_order_cart_info.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     * Database Column Remarks:
     *   当前会员等级价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_order_cart_info.user_price
     *
     * @mbg.generated
     */
    private BigDecimal userPrice;

    /**
     * Database Column Remarks:
     *   上级会员价格（一级）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_order_cart_info.one_price
     *
     * @mbg.generated
     */
    private BigDecimal onePrice;

    /**
     * Database Column Remarks:
     *   上上级会员价格（二级）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_order_cart_info.two_price
     *
     * @mbg.generated
     */
    private BigDecimal twoPrice;

    /**
     * Database Column Remarks:
     *   一级会员佣金
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_order_cart_info.distribute_1
     *
     * @mbg.generated
     */
    private BigDecimal distribute1;

    /**
     * Database Column Remarks:
     *   二级会员佣金
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_order_cart_info.distribute_2
     *
     * @mbg.generated
     */
    private BigDecimal distribute2;

    /**
     * Database Column Remarks:
     *   唯一id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_order_cart_info.unique
     *
     * @mbg.generated
     */
    private String unique;

    /**
     * Database Column Remarks:
     *   购物车标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_order_cart_info.order_cart_key
     *
     * @mbg.generated
     */
    private String orderCartKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_order_cart_info.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * Database Column Remarks:
     *   购买东西的详细信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_order_cart_info.cart_info
     *
     * @mbg.generated
     */
    private String cartInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_order_cart_info.oid
     *
     * @return the value of eb_store_order_cart_info.oid
     *
     * @mbg.generated
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_order_cart_info.oid
     *
     * @param oid the value for eb_store_order_cart_info.oid
     *
     * @mbg.generated
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_order_cart_info.cart_id
     *
     * @return the value of eb_store_order_cart_info.cart_id
     *
     * @mbg.generated
     */
    public Integer getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_order_cart_info.cart_id
     *
     * @param cartId the value for eb_store_order_cart_info.cart_id
     *
     * @mbg.generated
     */
    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_order_cart_info.product_id
     *
     * @return the value of eb_store_order_cart_info.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_order_cart_info.product_id
     *
     * @param productId the value for eb_store_order_cart_info.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_order_cart_info.user_price
     *
     * @return the value of eb_store_order_cart_info.user_price
     *
     * @mbg.generated
     */
    public BigDecimal getUserPrice() {
        return userPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_order_cart_info.user_price
     *
     * @param userPrice the value for eb_store_order_cart_info.user_price
     *
     * @mbg.generated
     */
    public void setUserPrice(BigDecimal userPrice) {
        this.userPrice = userPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_order_cart_info.one_price
     *
     * @return the value of eb_store_order_cart_info.one_price
     *
     * @mbg.generated
     */
    public BigDecimal getOnePrice() {
        return onePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_order_cart_info.one_price
     *
     * @param onePrice the value for eb_store_order_cart_info.one_price
     *
     * @mbg.generated
     */
    public void setOnePrice(BigDecimal onePrice) {
        this.onePrice = onePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_order_cart_info.two_price
     *
     * @return the value of eb_store_order_cart_info.two_price
     *
     * @mbg.generated
     */
    public BigDecimal getTwoPrice() {
        return twoPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_order_cart_info.two_price
     *
     * @param twoPrice the value for eb_store_order_cart_info.two_price
     *
     * @mbg.generated
     */
    public void setTwoPrice(BigDecimal twoPrice) {
        this.twoPrice = twoPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_order_cart_info.distribute_1
     *
     * @return the value of eb_store_order_cart_info.distribute_1
     *
     * @mbg.generated
     */
    public BigDecimal getDistribute1() {
        return distribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_order_cart_info.distribute_1
     *
     * @param distribute1 the value for eb_store_order_cart_info.distribute_1
     *
     * @mbg.generated
     */
    public void setDistribute1(BigDecimal distribute1) {
        this.distribute1 = distribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_order_cart_info.distribute_2
     *
     * @return the value of eb_store_order_cart_info.distribute_2
     *
     * @mbg.generated
     */
    public BigDecimal getDistribute2() {
        return distribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_order_cart_info.distribute_2
     *
     * @param distribute2 the value for eb_store_order_cart_info.distribute_2
     *
     * @mbg.generated
     */
    public void setDistribute2(BigDecimal distribute2) {
        this.distribute2 = distribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_order_cart_info.unique
     *
     * @return the value of eb_store_order_cart_info.unique
     *
     * @mbg.generated
     */
    public String getUnique() {
        return unique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_order_cart_info.unique
     *
     * @param unique the value for eb_store_order_cart_info.unique
     *
     * @mbg.generated
     */
    public void setUnique(String unique) {
        this.unique = unique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_order_cart_info.order_cart_key
     *
     * @return the value of eb_store_order_cart_info.order_cart_key
     *
     * @mbg.generated
     */
    public String getOrderCartKey() {
        return orderCartKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_order_cart_info.order_cart_key
     *
     * @param orderCartKey the value for eb_store_order_cart_info.order_cart_key
     *
     * @mbg.generated
     */
    public void setOrderCartKey(String orderCartKey) {
        this.orderCartKey = orderCartKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_order_cart_info.ctime
     *
     * @return the value of eb_store_order_cart_info.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_order_cart_info.ctime
     *
     * @param ctime the value for eb_store_order_cart_info.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_order_cart_info.cart_info
     *
     * @return the value of eb_store_order_cart_info.cart_info
     *
     * @mbg.generated
     */
    public String getCartInfo() {
        return cartInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_order_cart_info.cart_info
     *
     * @param cartInfo the value for eb_store_order_cart_info.cart_info
     *
     * @mbg.generated
     */
    public void setCartInfo(String cartInfo) {
        this.cartInfo = cartInfo;
    }
}