package com.enjoylearning.mybatis.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_system_user_level
 */
public class EbSystemUserLevel extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   商户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.mer_id
     *
     * @mbg.generated
     */
    private Integer merId;

    /**
     * Database Column Remarks:
     *   会员名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   购买金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.money
     *
     * @mbg.generated
     */
    private BigDecimal money;

    /**
     * Database Column Remarks:
     *   有效时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.valid_date
     *
     * @mbg.generated
     */
    private Integer validDate;

    /**
     * Database Column Remarks:
     *   是否为永久会员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.is_forever
     *
     * @mbg.generated
     */
    private Boolean isForever;

    /**
     * Database Column Remarks:
     *   是否购买,1=购买,0=不购买
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.is_pay
     *
     * @mbg.generated
     */
    private Boolean isPay;

    /**
     * Database Column Remarks:
     *   是否显示 1=显示,0=隐藏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.is_show
     *
     * @mbg.generated
     */
    private Boolean isShow;

    /**
     * Database Column Remarks:
     *   会员等级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.grade
     *
     * @mbg.generated
     */
    private Integer grade;

    /**
     * Database Column Remarks:
     *   享受折扣
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.discount
     *
     * @mbg.generated
     */
    private BigDecimal discount;

    /**
     * Database Column Remarks:
     *   个人业绩
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.performance
     *
     * @mbg.generated
     */
    private BigDecimal performance;

    /**
     * Database Column Remarks:
     *   团队业绩
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.group_performance
     *
     * @mbg.generated
     */
    private BigDecimal groupPerformance;

    /**
     * Database Column Remarks:
     *   团队人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.group_number
     *
     * @mbg.generated
     */
    private Integer groupNumber;

    /**
     * Database Column Remarks:
     *   会员卡背景
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.image
     *
     * @mbg.generated
     */
    private String image;

    /**
     * Database Column Remarks:
     *   会员图标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     * Database Column Remarks:
     *   添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     * Database Column Remarks:
     *   是否删除.1=删除,0=未删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.is_del
     *
     * @mbg.generated
     */
    private Boolean isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * Database Column Remarks:
     *   说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_user_level.explain
     *
     * @mbg.generated
     */
    private String explain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.id
     *
     * @return the value of eb_system_user_level.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.id
     *
     * @param id the value for eb_system_user_level.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.mer_id
     *
     * @return the value of eb_system_user_level.mer_id
     *
     * @mbg.generated
     */
    public Integer getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.mer_id
     *
     * @param merId the value for eb_system_user_level.mer_id
     *
     * @mbg.generated
     */
    public void setMerId(Integer merId) {
        this.merId = merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.name
     *
     * @return the value of eb_system_user_level.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.name
     *
     * @param name the value for eb_system_user_level.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.money
     *
     * @return the value of eb_system_user_level.money
     *
     * @mbg.generated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.money
     *
     * @param money the value for eb_system_user_level.money
     *
     * @mbg.generated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.valid_date
     *
     * @return the value of eb_system_user_level.valid_date
     *
     * @mbg.generated
     */
    public Integer getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.valid_date
     *
     * @param validDate the value for eb_system_user_level.valid_date
     *
     * @mbg.generated
     */
    public void setValidDate(Integer validDate) {
        this.validDate = validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.is_forever
     *
     * @return the value of eb_system_user_level.is_forever
     *
     * @mbg.generated
     */
    public Boolean getIsForever() {
        return isForever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.is_forever
     *
     * @param isForever the value for eb_system_user_level.is_forever
     *
     * @mbg.generated
     */
    public void setIsForever(Boolean isForever) {
        this.isForever = isForever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.is_pay
     *
     * @return the value of eb_system_user_level.is_pay
     *
     * @mbg.generated
     */
    public Boolean getIsPay() {
        return isPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.is_pay
     *
     * @param isPay the value for eb_system_user_level.is_pay
     *
     * @mbg.generated
     */
    public void setIsPay(Boolean isPay) {
        this.isPay = isPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.is_show
     *
     * @return the value of eb_system_user_level.is_show
     *
     * @mbg.generated
     */
    public Boolean getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.is_show
     *
     * @param isShow the value for eb_system_user_level.is_show
     *
     * @mbg.generated
     */
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.grade
     *
     * @return the value of eb_system_user_level.grade
     *
     * @mbg.generated
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.grade
     *
     * @param grade the value for eb_system_user_level.grade
     *
     * @mbg.generated
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.discount
     *
     * @return the value of eb_system_user_level.discount
     *
     * @mbg.generated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.discount
     *
     * @param discount the value for eb_system_user_level.discount
     *
     * @mbg.generated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.performance
     *
     * @return the value of eb_system_user_level.performance
     *
     * @mbg.generated
     */
    public BigDecimal getPerformance() {
        return performance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.performance
     *
     * @param performance the value for eb_system_user_level.performance
     *
     * @mbg.generated
     */
    public void setPerformance(BigDecimal performance) {
        this.performance = performance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.group_performance
     *
     * @return the value of eb_system_user_level.group_performance
     *
     * @mbg.generated
     */
    public BigDecimal getGroupPerformance() {
        return groupPerformance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.group_performance
     *
     * @param groupPerformance the value for eb_system_user_level.group_performance
     *
     * @mbg.generated
     */
    public void setGroupPerformance(BigDecimal groupPerformance) {
        this.groupPerformance = groupPerformance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.group_number
     *
     * @return the value of eb_system_user_level.group_number
     *
     * @mbg.generated
     */
    public Integer getGroupNumber() {
        return groupNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.group_number
     *
     * @param groupNumber the value for eb_system_user_level.group_number
     *
     * @mbg.generated
     */
    public void setGroupNumber(Integer groupNumber) {
        this.groupNumber = groupNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.image
     *
     * @return the value of eb_system_user_level.image
     *
     * @mbg.generated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.image
     *
     * @param image the value for eb_system_user_level.image
     *
     * @mbg.generated
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.icon
     *
     * @return the value of eb_system_user_level.icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.icon
     *
     * @param icon the value for eb_system_user_level.icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.add_time
     *
     * @return the value of eb_system_user_level.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.add_time
     *
     * @param addTime the value for eb_system_user_level.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.is_del
     *
     * @return the value of eb_system_user_level.is_del
     *
     * @mbg.generated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.is_del
     *
     * @param isDel the value for eb_system_user_level.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.ctime
     *
     * @return the value of eb_system_user_level.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.ctime
     *
     * @param ctime the value for eb_system_user_level.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_user_level.explain
     *
     * @return the value of eb_system_user_level.explain
     *
     * @mbg.generated
     */
    public String getExplain() {
        return explain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_user_level.explain
     *
     * @param explain the value for eb_system_user_level.explain
     *
     * @mbg.generated
     */
    public void setExplain(String explain) {
        this.explain = explain;
    }
}