package com.enjoylearning.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_system_notice
 */
public class EbSystemNotice extends BaseEntity {
    /**
     * Database Column Remarks:
     *   通知模板id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_notice.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   通知标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_notice.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   通知类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_notice.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   图标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_notice.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     * Database Column Remarks:
     *   链接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_notice.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * Database Column Remarks:
     *   通知数据
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_notice.table_title
     *
     * @mbg.generated
     */
    private String tableTitle;

    /**
     * Database Column Remarks:
     *   通知模板
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_notice.template
     *
     * @mbg.generated
     */
    private String template;

    /**
     * Database Column Remarks:
     *   通知管理员id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_notice.push_admin
     *
     * @mbg.generated
     */
    private String pushAdmin;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_notice.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_notice.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_notice.id
     *
     * @return the value of eb_system_notice.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_notice.id
     *
     * @param id the value for eb_system_notice.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_notice.title
     *
     * @return the value of eb_system_notice.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_notice.title
     *
     * @param title the value for eb_system_notice.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_notice.type
     *
     * @return the value of eb_system_notice.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_notice.type
     *
     * @param type the value for eb_system_notice.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_notice.icon
     *
     * @return the value of eb_system_notice.icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_notice.icon
     *
     * @param icon the value for eb_system_notice.icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_notice.url
     *
     * @return the value of eb_system_notice.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_notice.url
     *
     * @param url the value for eb_system_notice.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_notice.table_title
     *
     * @return the value of eb_system_notice.table_title
     *
     * @mbg.generated
     */
    public String getTableTitle() {
        return tableTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_notice.table_title
     *
     * @param tableTitle the value for eb_system_notice.table_title
     *
     * @mbg.generated
     */
    public void setTableTitle(String tableTitle) {
        this.tableTitle = tableTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_notice.template
     *
     * @return the value of eb_system_notice.template
     *
     * @mbg.generated
     */
    public String getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_notice.template
     *
     * @param template the value for eb_system_notice.template
     *
     * @mbg.generated
     */
    public void setTemplate(String template) {
        this.template = template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_notice.push_admin
     *
     * @return the value of eb_system_notice.push_admin
     *
     * @mbg.generated
     */
    public String getPushAdmin() {
        return pushAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_notice.push_admin
     *
     * @param pushAdmin the value for eb_system_notice.push_admin
     *
     * @mbg.generated
     */
    public void setPushAdmin(String pushAdmin) {
        this.pushAdmin = pushAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_notice.status
     *
     * @return the value of eb_system_notice.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_notice.status
     *
     * @param status the value for eb_system_notice.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_notice.ctime
     *
     * @return the value of eb_system_notice.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_notice.ctime
     *
     * @param ctime the value for eb_system_notice.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}