package com.enjoylearning.mybatis.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_system_file
 */
public class EbSystemFile extends BaseEntity {
    /**
     * Database Column Remarks:
     *   文件对比ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_file.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   文件内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_file.cthash
     *
     * @mbg.generated
     */
    private String cthash;

    /**
     * Database Column Remarks:
     *   文价名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_file.filename
     *
     * @mbg.generated
     */
    private String filename;

    /**
     * Database Column Remarks:
     *   上次访问时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_file.atime
     *
     * @mbg.generated
     */
    private String atime;

    /**
     * Database Column Remarks:
     *   上次修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_file.mtime
     *
     * @mbg.generated
     */
    private String mtime;

    /**
     * Database Column Remarks:
     *   上次改变时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_file.ctime
     *
     * @mbg.generated
     */
    private String ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_file.id
     *
     * @return the value of eb_system_file.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_file.id
     *
     * @param id the value for eb_system_file.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_file.cthash
     *
     * @return the value of eb_system_file.cthash
     *
     * @mbg.generated
     */
    public String getCthash() {
        return cthash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_file.cthash
     *
     * @param cthash the value for eb_system_file.cthash
     *
     * @mbg.generated
     */
    public void setCthash(String cthash) {
        this.cthash = cthash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_file.filename
     *
     * @return the value of eb_system_file.filename
     *
     * @mbg.generated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_file.filename
     *
     * @param filename the value for eb_system_file.filename
     *
     * @mbg.generated
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_file.atime
     *
     * @return the value of eb_system_file.atime
     *
     * @mbg.generated
     */
    public String getAtime() {
        return atime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_file.atime
     *
     * @param atime the value for eb_system_file.atime
     *
     * @mbg.generated
     */
    public void setAtime(String atime) {
        this.atime = atime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_file.mtime
     *
     * @return the value of eb_system_file.mtime
     *
     * @mbg.generated
     */
    public String getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_file.mtime
     *
     * @param mtime the value for eb_system_file.mtime
     *
     * @mbg.generated
     */
    public void setMtime(String mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_file.ctime
     *
     * @return the value of eb_system_file.ctime
     *
     * @mbg.generated
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_file.ctime
     *
     * @param ctime the value for eb_system_file.ctime
     *
     * @mbg.generated
     */
    public void setCtime(String ctime) {
        this.ctime = ctime;
    }
}