package com.enjoylearning.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_system_config_tab
 */
public class EbSystemConfigTab extends BaseEntity {
    /**
     * Database Column Remarks:
     *   配置分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_config_tab.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   配置分类名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_config_tab.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   配置分类英文名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_config_tab.eng_title
     *
     * @mbg.generated
     */
    private String engTitle;

    /**
     * Database Column Remarks:
     *   配置分类状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_config_tab.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   配置分类是否显示
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_config_tab.info
     *
     * @mbg.generated
     */
    private Boolean info;

    /**
     * Database Column Remarks:
     *   图标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_config_tab.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     * Database Column Remarks:
     *   配置类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_config_tab.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_config_tab.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_config_tab.id
     *
     * @return the value of eb_system_config_tab.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_config_tab.id
     *
     * @param id the value for eb_system_config_tab.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_config_tab.title
     *
     * @return the value of eb_system_config_tab.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_config_tab.title
     *
     * @param title the value for eb_system_config_tab.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_config_tab.eng_title
     *
     * @return the value of eb_system_config_tab.eng_title
     *
     * @mbg.generated
     */
    public String getEngTitle() {
        return engTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_config_tab.eng_title
     *
     * @param engTitle the value for eb_system_config_tab.eng_title
     *
     * @mbg.generated
     */
    public void setEngTitle(String engTitle) {
        this.engTitle = engTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_config_tab.status
     *
     * @return the value of eb_system_config_tab.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_config_tab.status
     *
     * @param status the value for eb_system_config_tab.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_config_tab.info
     *
     * @return the value of eb_system_config_tab.info
     *
     * @mbg.generated
     */
    public Boolean getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_config_tab.info
     *
     * @param info the value for eb_system_config_tab.info
     *
     * @mbg.generated
     */
    public void setInfo(Boolean info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_config_tab.icon
     *
     * @return the value of eb_system_config_tab.icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_config_tab.icon
     *
     * @param icon the value for eb_system_config_tab.icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_config_tab.type
     *
     * @return the value of eb_system_config_tab.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_config_tab.type
     *
     * @param type the value for eb_system_config_tab.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_config_tab.ctime
     *
     * @return the value of eb_system_config_tab.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_config_tab.ctime
     *
     * @param ctime the value for eb_system_config_tab.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}