package com.enjoylearning.mybatis.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_user_recharge
 */
public class EbUserRecharge extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_recharge.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   充值用户UID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_recharge.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_recharge.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     * Database Column Remarks:
     *   充值金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_recharge.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   充值类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_recharge.recharge_type
     *
     * @mbg.generated
     */
    private String rechargeType;

    /**
     * Database Column Remarks:
     *   是否充值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_recharge.paid
     *
     * @mbg.generated
     */
    private Boolean paid;

    /**
     * Database Column Remarks:
     *   充值支付时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_recharge.pay_time
     *
     * @mbg.generated
     */
    private Integer payTime;

    /**
     * Database Column Remarks:
     *   充值时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_recharge.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     * Database Column Remarks:
     *   退款金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_recharge.refund_price
     *
     * @mbg.generated
     */
    private BigDecimal refundPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_recharge.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_recharge.id
     *
     * @return the value of eb_user_recharge.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_recharge.id
     *
     * @param id the value for eb_user_recharge.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_recharge.uid
     *
     * @return the value of eb_user_recharge.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_recharge.uid
     *
     * @param uid the value for eb_user_recharge.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_recharge.order_id
     *
     * @return the value of eb_user_recharge.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_recharge.order_id
     *
     * @param orderId the value for eb_user_recharge.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_recharge.price
     *
     * @return the value of eb_user_recharge.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_recharge.price
     *
     * @param price the value for eb_user_recharge.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_recharge.recharge_type
     *
     * @return the value of eb_user_recharge.recharge_type
     *
     * @mbg.generated
     */
    public String getRechargeType() {
        return rechargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_recharge.recharge_type
     *
     * @param rechargeType the value for eb_user_recharge.recharge_type
     *
     * @mbg.generated
     */
    public void setRechargeType(String rechargeType) {
        this.rechargeType = rechargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_recharge.paid
     *
     * @return the value of eb_user_recharge.paid
     *
     * @mbg.generated
     */
    public Boolean getPaid() {
        return paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_recharge.paid
     *
     * @param paid the value for eb_user_recharge.paid
     *
     * @mbg.generated
     */
    public void setPaid(Boolean paid) {
        this.paid = paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_recharge.pay_time
     *
     * @return the value of eb_user_recharge.pay_time
     *
     * @mbg.generated
     */
    public Integer getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_recharge.pay_time
     *
     * @param payTime the value for eb_user_recharge.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(Integer payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_recharge.add_time
     *
     * @return the value of eb_user_recharge.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_recharge.add_time
     *
     * @param addTime the value for eb_user_recharge.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_recharge.refund_price
     *
     * @return the value of eb_user_recharge.refund_price
     *
     * @mbg.generated
     */
    public BigDecimal getRefundPrice() {
        return refundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_recharge.refund_price
     *
     * @param refundPrice the value for eb_user_recharge.refund_price
     *
     * @mbg.generated
     */
    public void setRefundPrice(BigDecimal refundPrice) {
        this.refundPrice = refundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_recharge.ctime
     *
     * @return the value of eb_user_recharge.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_recharge.ctime
     *
     * @param ctime the value for eb_user_recharge.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}