package com.enjoylearning.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_user_enter
 */
public class EbUserEnter extends BaseEntity {
    /**
     * Database Column Remarks:
     *   商户申请ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   商户所在省
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     * Database Column Remarks:
     *   商户所在市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     * Database Column Remarks:
     *   商户所在区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.district
     *
     * @mbg.generated
     */
    private String district;

    /**
     * Database Column Remarks:
     *   商户详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   商户名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.merchant_name
     *
     * @mbg.generated
     */
    private String merchantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.link_user
     *
     * @mbg.generated
     */
    private String linkUser;

    /**
     * Database Column Remarks:
     *   商户电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.link_tel
     *
     * @mbg.generated
     */
    private String linkTel;

    /**
     * Database Column Remarks:
     *   商户证书
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.charter
     *
     * @mbg.generated
     */
    private String charter;

    /**
     * Database Column Remarks:
     *   添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     * Database Column Remarks:
     *   审核时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.apply_time
     *
     * @mbg.generated
     */
    private Integer applyTime;

    /**
     * Database Column Remarks:
     *   通过时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.success_time
     *
     * @mbg.generated
     */
    private Integer successTime;

    /**
     * Database Column Remarks:
     *   未通过原因
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.fail_message
     *
     * @mbg.generated
     */
    private String failMessage;

    /**
     * Database Column Remarks:
     *   未通过时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.fail_time
     *
     * @mbg.generated
     */
    private Integer failTime;

    /**
     * Database Column Remarks:
     *   -1 审核未通过 0未审核 1审核通过
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   0 = 开启 1= 关闭
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.is_lock
     *
     * @mbg.generated
     */
    private Boolean isLock;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.is_del
     *
     * @mbg.generated
     */
    private Boolean isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_enter.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.id
     *
     * @return the value of eb_user_enter.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.id
     *
     * @param id the value for eb_user_enter.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.uid
     *
     * @return the value of eb_user_enter.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.uid
     *
     * @param uid the value for eb_user_enter.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.province
     *
     * @return the value of eb_user_enter.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.province
     *
     * @param province the value for eb_user_enter.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.city
     *
     * @return the value of eb_user_enter.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.city
     *
     * @param city the value for eb_user_enter.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.district
     *
     * @return the value of eb_user_enter.district
     *
     * @mbg.generated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.district
     *
     * @param district the value for eb_user_enter.district
     *
     * @mbg.generated
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.address
     *
     * @return the value of eb_user_enter.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.address
     *
     * @param address the value for eb_user_enter.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.merchant_name
     *
     * @return the value of eb_user_enter.merchant_name
     *
     * @mbg.generated
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.merchant_name
     *
     * @param merchantName the value for eb_user_enter.merchant_name
     *
     * @mbg.generated
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.link_user
     *
     * @return the value of eb_user_enter.link_user
     *
     * @mbg.generated
     */
    public String getLinkUser() {
        return linkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.link_user
     *
     * @param linkUser the value for eb_user_enter.link_user
     *
     * @mbg.generated
     */
    public void setLinkUser(String linkUser) {
        this.linkUser = linkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.link_tel
     *
     * @return the value of eb_user_enter.link_tel
     *
     * @mbg.generated
     */
    public String getLinkTel() {
        return linkTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.link_tel
     *
     * @param linkTel the value for eb_user_enter.link_tel
     *
     * @mbg.generated
     */
    public void setLinkTel(String linkTel) {
        this.linkTel = linkTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.charter
     *
     * @return the value of eb_user_enter.charter
     *
     * @mbg.generated
     */
    public String getCharter() {
        return charter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.charter
     *
     * @param charter the value for eb_user_enter.charter
     *
     * @mbg.generated
     */
    public void setCharter(String charter) {
        this.charter = charter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.add_time
     *
     * @return the value of eb_user_enter.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.add_time
     *
     * @param addTime the value for eb_user_enter.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.apply_time
     *
     * @return the value of eb_user_enter.apply_time
     *
     * @mbg.generated
     */
    public Integer getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.apply_time
     *
     * @param applyTime the value for eb_user_enter.apply_time
     *
     * @mbg.generated
     */
    public void setApplyTime(Integer applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.success_time
     *
     * @return the value of eb_user_enter.success_time
     *
     * @mbg.generated
     */
    public Integer getSuccessTime() {
        return successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.success_time
     *
     * @param successTime the value for eb_user_enter.success_time
     *
     * @mbg.generated
     */
    public void setSuccessTime(Integer successTime) {
        this.successTime = successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.fail_message
     *
     * @return the value of eb_user_enter.fail_message
     *
     * @mbg.generated
     */
    public String getFailMessage() {
        return failMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.fail_message
     *
     * @param failMessage the value for eb_user_enter.fail_message
     *
     * @mbg.generated
     */
    public void setFailMessage(String failMessage) {
        this.failMessage = failMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.fail_time
     *
     * @return the value of eb_user_enter.fail_time
     *
     * @mbg.generated
     */
    public Integer getFailTime() {
        return failTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.fail_time
     *
     * @param failTime the value for eb_user_enter.fail_time
     *
     * @mbg.generated
     */
    public void setFailTime(Integer failTime) {
        this.failTime = failTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.status
     *
     * @return the value of eb_user_enter.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.status
     *
     * @param status the value for eb_user_enter.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.is_lock
     *
     * @return the value of eb_user_enter.is_lock
     *
     * @mbg.generated
     */
    public Boolean getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.is_lock
     *
     * @param isLock the value for eb_user_enter.is_lock
     *
     * @mbg.generated
     */
    public void setIsLock(Boolean isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.is_del
     *
     * @return the value of eb_user_enter.is_del
     *
     * @mbg.generated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.is_del
     *
     * @param isDel the value for eb_user_enter.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_enter.ctime
     *
     * @return the value of eb_user_enter.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_enter.ctime
     *
     * @param ctime the value for eb_user_enter.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}