package com.enjoylearning.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_user_notice_see
 */
public class EbUserNoticeSee extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_notice_see.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   查看的通知id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_notice_see.nid
     *
     * @mbg.generated
     */
    private Integer nid;

    /**
     * Database Column Remarks:
     *   查看通知的用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_notice_see.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   查看通知的时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_notice_see.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_notice_see.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_notice_see.id
     *
     * @return the value of eb_user_notice_see.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_notice_see.id
     *
     * @param id the value for eb_user_notice_see.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_notice_see.nid
     *
     * @return the value of eb_user_notice_see.nid
     *
     * @mbg.generated
     */
    public Integer getNid() {
        return nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_notice_see.nid
     *
     * @param nid the value for eb_user_notice_see.nid
     *
     * @mbg.generated
     */
    public void setNid(Integer nid) {
        this.nid = nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_notice_see.uid
     *
     * @return the value of eb_user_notice_see.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_notice_see.uid
     *
     * @param uid the value for eb_user_notice_see.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_notice_see.add_time
     *
     * @return the value of eb_user_notice_see.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_notice_see.add_time
     *
     * @param addTime the value for eb_user_notice_see.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_notice_see.ctime
     *
     * @return the value of eb_user_notice_see.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_notice_see.ctime
     *
     * @param ctime the value for eb_user_notice_see.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}