package com.enjoylearning.mybatis.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_user
 */
public class EbUser extends BaseEntity {
    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   用户账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     * Database Column Remarks:
     *   用户密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.pwd
     *
     * @mbg.generated
     */
    private String pwd;

    /**
     * Database Column Remarks:
     *   真实姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     * Database Column Remarks:
     *   生日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.birthday
     *
     * @mbg.generated
     */
    private Integer birthday;

    /**
     * Database Column Remarks:
     *   身份证号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.card_id
     *
     * @mbg.generated
     */
    private String cardId;

    /**
     * Database Column Remarks:
     *   用户备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     * Database Column Remarks:
     *   合伙人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.partner_id
     *
     * @mbg.generated
     */
    private Integer partnerId;

    /**
     * Database Column Remarks:
     *   用户分组id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     * Database Column Remarks:
     *   用户昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     * Database Column Remarks:
     *   用户头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     * Database Column Remarks:
     *   手机号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     * Database Column Remarks:
     *   添加ip
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.add_ip
     *
     * @mbg.generated
     */
    private String addIp;

    /**
     * Database Column Remarks:
     *   最后一次登录时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.last_time
     *
     * @mbg.generated
     */
    private Integer lastTime;

    /**
     * Database Column Remarks:
     *   最后一次登录ip
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.last_ip
     *
     * @mbg.generated
     */
    private String lastIp;

    /**
     * Database Column Remarks:
     *   用户余额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.now_money
     *
     * @mbg.generated
     */
    private BigDecimal nowMoney;

    /**
     * Database Column Remarks:
     *   用户剩余积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.integral
     *
     * @mbg.generated
     */
    private BigDecimal integral;

    /**
     * Database Column Remarks:
     *   连续签到天数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.sign_num
     *
     * @mbg.generated
     */
    private Integer signNum;

    /**
     * Database Column Remarks:
     *   1为正常，0为禁止
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   等级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.level
     *
     * @mbg.generated
     */
    private Byte level;

    /**
     * Database Column Remarks:
     *   推广元id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.spread_uid
     *
     * @mbg.generated
     */
    private Integer spreadUid;

    /**
     * Database Column Remarks:
     *   推广员关联时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.spread_time
     *
     * @mbg.generated
     */
    private Integer spreadTime;

    /**
     * Database Column Remarks:
     *   用户类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.user_type
     *
     * @mbg.generated
     */
    private String userType;

    /**
     * Database Column Remarks:
     *   是否为推广员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.is_promoter
     *
     * @mbg.generated
     */
    private Boolean isPromoter;

    /**
     * Database Column Remarks:
     *   用户购买次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.pay_count
     *
     * @mbg.generated
     */
    private Integer payCount;

    /**
     * Database Column Remarks:
     *   下级人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.spread_count
     *
     * @mbg.generated
     */
    private Integer spreadCount;

    /**
     * Database Column Remarks:
     *   等级清除时间为0没有清除过
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.clean_time
     *
     * @mbg.generated
     */
    private Integer cleanTime;

    /**
     * Database Column Remarks:
     *   详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.addres
     *
     * @mbg.generated
     */
    private String addres;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.uid
     *
     * @return the value of eb_user.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.uid
     *
     * @param uid the value for eb_user.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.account
     *
     * @return the value of eb_user.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.account
     *
     * @param account the value for eb_user.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.pwd
     *
     * @return the value of eb_user.pwd
     *
     * @mbg.generated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.pwd
     *
     * @param pwd the value for eb_user.pwd
     *
     * @mbg.generated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.real_name
     *
     * @return the value of eb_user.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.real_name
     *
     * @param realName the value for eb_user.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.birthday
     *
     * @return the value of eb_user.birthday
     *
     * @mbg.generated
     */
    public Integer getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.birthday
     *
     * @param birthday the value for eb_user.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Integer birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.card_id
     *
     * @return the value of eb_user.card_id
     *
     * @mbg.generated
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.card_id
     *
     * @param cardId the value for eb_user.card_id
     *
     * @mbg.generated
     */
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.mark
     *
     * @return the value of eb_user.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.mark
     *
     * @param mark the value for eb_user.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.partner_id
     *
     * @return the value of eb_user.partner_id
     *
     * @mbg.generated
     */
    public Integer getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.partner_id
     *
     * @param partnerId the value for eb_user.partner_id
     *
     * @mbg.generated
     */
    public void setPartnerId(Integer partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.group_id
     *
     * @return the value of eb_user.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.group_id
     *
     * @param groupId the value for eb_user.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.nickname
     *
     * @return the value of eb_user.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.nickname
     *
     * @param nickname the value for eb_user.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.avatar
     *
     * @return the value of eb_user.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.avatar
     *
     * @param avatar the value for eb_user.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.phone
     *
     * @return the value of eb_user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.phone
     *
     * @param phone the value for eb_user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.add_time
     *
     * @return the value of eb_user.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.add_time
     *
     * @param addTime the value for eb_user.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.add_ip
     *
     * @return the value of eb_user.add_ip
     *
     * @mbg.generated
     */
    public String getAddIp() {
        return addIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.add_ip
     *
     * @param addIp the value for eb_user.add_ip
     *
     * @mbg.generated
     */
    public void setAddIp(String addIp) {
        this.addIp = addIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.last_time
     *
     * @return the value of eb_user.last_time
     *
     * @mbg.generated
     */
    public Integer getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.last_time
     *
     * @param lastTime the value for eb_user.last_time
     *
     * @mbg.generated
     */
    public void setLastTime(Integer lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.last_ip
     *
     * @return the value of eb_user.last_ip
     *
     * @mbg.generated
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.last_ip
     *
     * @param lastIp the value for eb_user.last_ip
     *
     * @mbg.generated
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.now_money
     *
     * @return the value of eb_user.now_money
     *
     * @mbg.generated
     */
    public BigDecimal getNowMoney() {
        return nowMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.now_money
     *
     * @param nowMoney the value for eb_user.now_money
     *
     * @mbg.generated
     */
    public void setNowMoney(BigDecimal nowMoney) {
        this.nowMoney = nowMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.integral
     *
     * @return the value of eb_user.integral
     *
     * @mbg.generated
     */
    public BigDecimal getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.integral
     *
     * @param integral the value for eb_user.integral
     *
     * @mbg.generated
     */
    public void setIntegral(BigDecimal integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.sign_num
     *
     * @return the value of eb_user.sign_num
     *
     * @mbg.generated
     */
    public Integer getSignNum() {
        return signNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.sign_num
     *
     * @param signNum the value for eb_user.sign_num
     *
     * @mbg.generated
     */
    public void setSignNum(Integer signNum) {
        this.signNum = signNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.status
     *
     * @return the value of eb_user.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.status
     *
     * @param status the value for eb_user.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.level
     *
     * @return the value of eb_user.level
     *
     * @mbg.generated
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.level
     *
     * @param level the value for eb_user.level
     *
     * @mbg.generated
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.spread_uid
     *
     * @return the value of eb_user.spread_uid
     *
     * @mbg.generated
     */
    public Integer getSpreadUid() {
        return spreadUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.spread_uid
     *
     * @param spreadUid the value for eb_user.spread_uid
     *
     * @mbg.generated
     */
    public void setSpreadUid(Integer spreadUid) {
        this.spreadUid = spreadUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.spread_time
     *
     * @return the value of eb_user.spread_time
     *
     * @mbg.generated
     */
    public Integer getSpreadTime() {
        return spreadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.spread_time
     *
     * @param spreadTime the value for eb_user.spread_time
     *
     * @mbg.generated
     */
    public void setSpreadTime(Integer spreadTime) {
        this.spreadTime = spreadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.user_type
     *
     * @return the value of eb_user.user_type
     *
     * @mbg.generated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.user_type
     *
     * @param userType the value for eb_user.user_type
     *
     * @mbg.generated
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.is_promoter
     *
     * @return the value of eb_user.is_promoter
     *
     * @mbg.generated
     */
    public Boolean getIsPromoter() {
        return isPromoter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.is_promoter
     *
     * @param isPromoter the value for eb_user.is_promoter
     *
     * @mbg.generated
     */
    public void setIsPromoter(Boolean isPromoter) {
        this.isPromoter = isPromoter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.pay_count
     *
     * @return the value of eb_user.pay_count
     *
     * @mbg.generated
     */
    public Integer getPayCount() {
        return payCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.pay_count
     *
     * @param payCount the value for eb_user.pay_count
     *
     * @mbg.generated
     */
    public void setPayCount(Integer payCount) {
        this.payCount = payCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.spread_count
     *
     * @return the value of eb_user.spread_count
     *
     * @mbg.generated
     */
    public Integer getSpreadCount() {
        return spreadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.spread_count
     *
     * @param spreadCount the value for eb_user.spread_count
     *
     * @mbg.generated
     */
    public void setSpreadCount(Integer spreadCount) {
        this.spreadCount = spreadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.clean_time
     *
     * @return the value of eb_user.clean_time
     *
     * @mbg.generated
     */
    public Integer getCleanTime() {
        return cleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.clean_time
     *
     * @param cleanTime the value for eb_user.clean_time
     *
     * @mbg.generated
     */
    public void setCleanTime(Integer cleanTime) {
        this.cleanTime = cleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.addres
     *
     * @return the value of eb_user.addres
     *
     * @mbg.generated
     */
    public String getAddres() {
        return addres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.addres
     *
     * @param addres the value for eb_user.addres
     *
     * @mbg.generated
     */
    public void setAddres(String addres) {
        this.addres = addres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.ctime
     *
     * @return the value of eb_user.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.ctime
     *
     * @param ctime the value for eb_user.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}