package com.enjoylearning.mybatis.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_user_extract
 */
public class EbUserExtract extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_extract.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_extract.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_extract.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     * Database Column Remarks:
     *   bank = 银行卡 alipay = 支付宝wx=微信
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_extract.extract_type
     *
     * @mbg.generated
     */
    private String extractType;

    /**
     * Database Column Remarks:
     *   银行卡
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_extract.bank_code
     *
     * @mbg.generated
     */
    private String bankCode;

    /**
     * Database Column Remarks:
     *   开户地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_extract.bank_address
     *
     * @mbg.generated
     */
    private String bankAddress;

    /**
     * Database Column Remarks:
     *   支付宝账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_extract.alipay_code
     *
     * @mbg.generated
     */
    private String alipayCode;

    /**
     * Database Column Remarks:
     *   提现金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_extract.extract_price
     *
     * @mbg.generated
     */
    private BigDecimal extractPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_extract.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_extract.balance
     *
     * @mbg.generated
     */
    private BigDecimal balance;

    /**
     * Database Column Remarks:
     *   无效原因
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_extract.fail_msg
     *
     * @mbg.generated
     */
    private String failMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_extract.fail_time
     *
     * @mbg.generated
     */
    private Integer failTime;

    /**
     * Database Column Remarks:
     *   添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_extract.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     * Database Column Remarks:
     *   -1 未通过 0 审核中 1 已提现
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_extract.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   微信号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_extract.wechat
     *
     * @mbg.generated
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_extract.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_extract.id
     *
     * @return the value of eb_user_extract.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_extract.id
     *
     * @param id the value for eb_user_extract.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_extract.uid
     *
     * @return the value of eb_user_extract.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_extract.uid
     *
     * @param uid the value for eb_user_extract.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_extract.real_name
     *
     * @return the value of eb_user_extract.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_extract.real_name
     *
     * @param realName the value for eb_user_extract.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_extract.extract_type
     *
     * @return the value of eb_user_extract.extract_type
     *
     * @mbg.generated
     */
    public String getExtractType() {
        return extractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_extract.extract_type
     *
     * @param extractType the value for eb_user_extract.extract_type
     *
     * @mbg.generated
     */
    public void setExtractType(String extractType) {
        this.extractType = extractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_extract.bank_code
     *
     * @return the value of eb_user_extract.bank_code
     *
     * @mbg.generated
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_extract.bank_code
     *
     * @param bankCode the value for eb_user_extract.bank_code
     *
     * @mbg.generated
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_extract.bank_address
     *
     * @return the value of eb_user_extract.bank_address
     *
     * @mbg.generated
     */
    public String getBankAddress() {
        return bankAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_extract.bank_address
     *
     * @param bankAddress the value for eb_user_extract.bank_address
     *
     * @mbg.generated
     */
    public void setBankAddress(String bankAddress) {
        this.bankAddress = bankAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_extract.alipay_code
     *
     * @return the value of eb_user_extract.alipay_code
     *
     * @mbg.generated
     */
    public String getAlipayCode() {
        return alipayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_extract.alipay_code
     *
     * @param alipayCode the value for eb_user_extract.alipay_code
     *
     * @mbg.generated
     */
    public void setAlipayCode(String alipayCode) {
        this.alipayCode = alipayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_extract.extract_price
     *
     * @return the value of eb_user_extract.extract_price
     *
     * @mbg.generated
     */
    public BigDecimal getExtractPrice() {
        return extractPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_extract.extract_price
     *
     * @param extractPrice the value for eb_user_extract.extract_price
     *
     * @mbg.generated
     */
    public void setExtractPrice(BigDecimal extractPrice) {
        this.extractPrice = extractPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_extract.mark
     *
     * @return the value of eb_user_extract.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_extract.mark
     *
     * @param mark the value for eb_user_extract.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_extract.balance
     *
     * @return the value of eb_user_extract.balance
     *
     * @mbg.generated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_extract.balance
     *
     * @param balance the value for eb_user_extract.balance
     *
     * @mbg.generated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_extract.fail_msg
     *
     * @return the value of eb_user_extract.fail_msg
     *
     * @mbg.generated
     */
    public String getFailMsg() {
        return failMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_extract.fail_msg
     *
     * @param failMsg the value for eb_user_extract.fail_msg
     *
     * @mbg.generated
     */
    public void setFailMsg(String failMsg) {
        this.failMsg = failMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_extract.fail_time
     *
     * @return the value of eb_user_extract.fail_time
     *
     * @mbg.generated
     */
    public Integer getFailTime() {
        return failTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_extract.fail_time
     *
     * @param failTime the value for eb_user_extract.fail_time
     *
     * @mbg.generated
     */
    public void setFailTime(Integer failTime) {
        this.failTime = failTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_extract.add_time
     *
     * @return the value of eb_user_extract.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_extract.add_time
     *
     * @param addTime the value for eb_user_extract.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_extract.status
     *
     * @return the value of eb_user_extract.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_extract.status
     *
     * @param status the value for eb_user_extract.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_extract.wechat
     *
     * @return the value of eb_user_extract.wechat
     *
     * @mbg.generated
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_extract.wechat
     *
     * @param wechat the value for eb_user_extract.wechat
     *
     * @mbg.generated
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_extract.ctime
     *
     * @return the value of eb_user_extract.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_extract.ctime
     *
     * @param ctime the value for eb_user_extract.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}