package com.enjoylearning.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_user_notice
 */
public class EbUserNotice extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_notice.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   消息通知类型（1：系统消息；2：用户通知）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_notice.type
     *
     * @mbg.generated
     */
    private Boolean type;

    /**
     * Database Column Remarks:
     *   发送人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_notice.user
     *
     * @mbg.generated
     */
    private String user;

    /**
     * Database Column Remarks:
     *   通知消息的标题信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_notice.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   通知消息的内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_notice.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   通知消息发送的时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_notice.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     * Database Column Remarks:
     *   是否发送（0：未发送；1：已发送）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_notice.is_send
     *
     * @mbg.generated
     */
    private Boolean isSend;

    /**
     * Database Column Remarks:
     *   发送时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_notice.send_time
     *
     * @mbg.generated
     */
    private Integer sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_notice.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * Database Column Remarks:
     *   接收消息的用户id（类型：json数据）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_notice.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_notice.id
     *
     * @return the value of eb_user_notice.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_notice.id
     *
     * @param id the value for eb_user_notice.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_notice.type
     *
     * @return the value of eb_user_notice.type
     *
     * @mbg.generated
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_notice.type
     *
     * @param type the value for eb_user_notice.type
     *
     * @mbg.generated
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_notice.user
     *
     * @return the value of eb_user_notice.user
     *
     * @mbg.generated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_notice.user
     *
     * @param user the value for eb_user_notice.user
     *
     * @mbg.generated
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_notice.title
     *
     * @return the value of eb_user_notice.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_notice.title
     *
     * @param title the value for eb_user_notice.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_notice.content
     *
     * @return the value of eb_user_notice.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_notice.content
     *
     * @param content the value for eb_user_notice.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_notice.add_time
     *
     * @return the value of eb_user_notice.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_notice.add_time
     *
     * @param addTime the value for eb_user_notice.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_notice.is_send
     *
     * @return the value of eb_user_notice.is_send
     *
     * @mbg.generated
     */
    public Boolean getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_notice.is_send
     *
     * @param isSend the value for eb_user_notice.is_send
     *
     * @mbg.generated
     */
    public void setIsSend(Boolean isSend) {
        this.isSend = isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_notice.send_time
     *
     * @return the value of eb_user_notice.send_time
     *
     * @mbg.generated
     */
    public Integer getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_notice.send_time
     *
     * @param sendTime the value for eb_user_notice.send_time
     *
     * @mbg.generated
     */
    public void setSendTime(Integer sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_notice.ctime
     *
     * @return the value of eb_user_notice.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_notice.ctime
     *
     * @param ctime the value for eb_user_notice.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_notice.uid
     *
     * @return the value of eb_user_notice.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_notice.uid
     *
     * @param uid the value for eb_user_notice.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }
}