package com.enjoylearning.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_user_address
 */
public class EbUserAddress extends BaseEntity {
    /**
     * Database Column Remarks:
     *   用户地址id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_address.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_address.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   收货人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_address.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     * Database Column Remarks:
     *   收货人电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_address.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   收货人所在省
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_address.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     * Database Column Remarks:
     *   收货人所在市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_address.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     * Database Column Remarks:
     *   收货人所在区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_address.district
     *
     * @mbg.generated
     */
    private String district;

    /**
     * Database Column Remarks:
     *   收货人详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_address.detail
     *
     * @mbg.generated
     */
    private String detail;

    /**
     * Database Column Remarks:
     *   邮编
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_address.post_code
     *
     * @mbg.generated
     */
    private Integer postCode;

    /**
     * Database Column Remarks:
     *   经度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_address.longitude
     *
     * @mbg.generated
     */
    private String longitude;

    /**
     * Database Column Remarks:
     *   纬度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_address.latitude
     *
     * @mbg.generated
     */
    private String latitude;

    /**
     * Database Column Remarks:
     *   是否默认
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_address.is_default
     *
     * @mbg.generated
     */
    private Boolean isDefault;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_address.is_del
     *
     * @mbg.generated
     */
    private Boolean isDel;

    /**
     * Database Column Remarks:
     *   添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_address.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user_address.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_address.id
     *
     * @return the value of eb_user_address.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_address.id
     *
     * @param id the value for eb_user_address.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_address.uid
     *
     * @return the value of eb_user_address.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_address.uid
     *
     * @param uid the value for eb_user_address.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_address.real_name
     *
     * @return the value of eb_user_address.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_address.real_name
     *
     * @param realName the value for eb_user_address.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_address.phone
     *
     * @return the value of eb_user_address.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_address.phone
     *
     * @param phone the value for eb_user_address.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_address.province
     *
     * @return the value of eb_user_address.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_address.province
     *
     * @param province the value for eb_user_address.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_address.city
     *
     * @return the value of eb_user_address.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_address.city
     *
     * @param city the value for eb_user_address.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_address.district
     *
     * @return the value of eb_user_address.district
     *
     * @mbg.generated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_address.district
     *
     * @param district the value for eb_user_address.district
     *
     * @mbg.generated
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_address.detail
     *
     * @return the value of eb_user_address.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_address.detail
     *
     * @param detail the value for eb_user_address.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_address.post_code
     *
     * @return the value of eb_user_address.post_code
     *
     * @mbg.generated
     */
    public Integer getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_address.post_code
     *
     * @param postCode the value for eb_user_address.post_code
     *
     * @mbg.generated
     */
    public void setPostCode(Integer postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_address.longitude
     *
     * @return the value of eb_user_address.longitude
     *
     * @mbg.generated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_address.longitude
     *
     * @param longitude the value for eb_user_address.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_address.latitude
     *
     * @return the value of eb_user_address.latitude
     *
     * @mbg.generated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_address.latitude
     *
     * @param latitude the value for eb_user_address.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_address.is_default
     *
     * @return the value of eb_user_address.is_default
     *
     * @mbg.generated
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_address.is_default
     *
     * @param isDefault the value for eb_user_address.is_default
     *
     * @mbg.generated
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_address.is_del
     *
     * @return the value of eb_user_address.is_del
     *
     * @mbg.generated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_address.is_del
     *
     * @param isDel the value for eb_user_address.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_address.add_time
     *
     * @return the value of eb_user_address.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_address.add_time
     *
     * @param addTime the value for eb_user_address.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user_address.ctime
     *
     * @return the value of eb_user_address.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user_address.ctime
     *
     * @param ctime the value for eb_user_address.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}