package com.enjoylearning.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table eb_wechat_message
 */
public class EbWechatMessage extends BaseEntity {
    /**
     * Database Column Remarks:
     *   用户行为记录id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_wechat_message.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户openid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_wechat_message.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     * Database Column Remarks:
     *   操作类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_wechat_message.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   操作详细记录
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_wechat_message.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_wechat_message.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_wechat_message.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_wechat_message.id
     *
     * @return the value of eb_wechat_message.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_wechat_message.id
     *
     * @param id the value for eb_wechat_message.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_wechat_message.openid
     *
     * @return the value of eb_wechat_message.openid
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_wechat_message.openid
     *
     * @param openid the value for eb_wechat_message.openid
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_wechat_message.type
     *
     * @return the value of eb_wechat_message.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_wechat_message.type
     *
     * @param type the value for eb_wechat_message.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_wechat_message.result
     *
     * @return the value of eb_wechat_message.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_wechat_message.result
     *
     * @param result the value for eb_wechat_message.result
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_wechat_message.add_time
     *
     * @return the value of eb_wechat_message.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_wechat_message.add_time
     *
     * @param addTime the value for eb_wechat_message.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_wechat_message.ctime
     *
     * @return the value of eb_wechat_message.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_wechat_message.ctime
     *
     * @param ctime the value for eb_wechat_message.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}